-- 美國市場推薦碼／折扣碼服務商清單 —— 200 筆
--
-- 這不是 migration，goose 不會碰它。要套用得自己開 psql 跑，而且跑下去就是
-- 動到正式那台（本專案沒有本機資料庫），套用前請整份看過。
--
-- 資料來源與時效（查證日：2026-08-23）：
--   * 熱門度排序取自 2026-08 美國 App Store 免費榜（m-s-y.com、apppricedata.com
--     兩份榜單交叉比對），榜上排名寫在每筆後面的註解，沒上榜但推薦制度成熟的
--     不標名次。榜單本身天天在動，這裡只當「先收哪些」的優先序，沒有存進資料庫
--     —— merchants 沒有熱門度欄位。
--   * 獎勵金額查證過的有：Chime $100、Uber Eats $20/$10、Instacart $10、
--     Grubhub $10、Mint Mobile $45/$15、Google Fi $60、Turo $300、Rakuten $50、
--     Ibotta $7、Dropbox 500MB、Wise £50/3 人。其餘只寫「制度是什麼」不寫死數字。
--   * 金額類敘述是各家最常見的檔期值，這種數字一季一變，上線前應逐家複核。
--   * signup_url 一律填官方主網域（少數確定的填官方 refer 頁），沒有逐一開過確認
--     —— 用 admin 後台一筆筆點過去比在這裡假裝驗過誠實。
--
-- 刻意排除：沒有推薦碼也沒有折扣碼制度的 app（Netflix、Google 系工具、
-- Microsoft 系工具、短劇類、純免費工具），榜上再高也不收 —— 收進來就是
-- 建一個永遠不會有碼的空商家頁。
--
-- 新增了一個分類「保險」，refcode-app/src/categories.ts 的 CATEGORY_ICONS
-- 目前比不到它（會 fallback 成通用圖示），要補一條 /保險|insurance|保険/。

BEGIN;

-- 分類沒有唯一約束（slug 在 00007 被拿掉了），直接 INSERT 重跑會長出重複，
-- 所以用 name 比對既有的。這跟 cmd/seed 的做法一致。
INSERT INTO referral_code_bonus.merchant_categories (name, name_en, name_ja, sort_order)
SELECT v.name, v.name_en, v.name_ja, v.sort_order
FROM (VALUES
    ('銀行信用卡', 'Banking & Cards',      '銀行・カード',        0),
    ('券商投資',   'Investing & Crypto',   '証券・投資',          1),
    ('外送',       'Food & Delivery',      'デリバリー・外食',    2),
    ('影音串流',   'Streaming',            '動画・音楽',          3),
    ('電信通訊',   'Telecom',              '通信・携帯',          4),
    ('旅遊訂房',   'Travel & Hotels',      '旅行・ホテル',        5),
    ('購物電商',   'Shopping',             '通販・ショッピング',  6),
    ('交通出行',   'Ride & Transport',     '移動・交通',          7),
    ('健康運動',   'Health & Fitness',     '健康・フィットネス',  8),
    ('學習教育',   'Learning',             '学習・教育',          9),
    ('軟體訂閱',   'Software & Cloud',     'SaaS・クラウド',     10),
    ('遊戲',       'Games',                'ゲーム',             11),
    ('工具生產力', 'Productivity',         '生産性・ビジネス',   12),
    ('保險',       'Insurance',            '保険',               13)
) AS v(name, name_en, name_ja, sort_order)
WHERE NOT EXISTS (
    SELECT 1 FROM referral_code_bonus.merchant_categories c WHERE c.name = v.name
);

-- countries 的語意見 00006_geo.sql：空陣列＝不分地區（跨國服務），排序時當中性。
-- 只在美國能用的填 {US}，Spotify、Dropbox 這種全球服務留空 —— 填 {US} 會讓
-- 台灣使用者看到它被當「外地服務商」壓到後面，那是錯的。
--
-- allowed_code_types 見 00014：只有一對一邀請制的填 {referral}，只有公開檔期
-- 折扣碼的填 {discount}，兩種都收的填兩個。填錯的後果是使用者投稿時被擋，
-- 或是投了一種平台不該收的碼。
INSERT INTO referral_code_bonus.merchants
    (slug, name, category_id, signup_url, reward_desc, reward_desc_en, reward_desc_ja,
     countries, allowed_code_types, is_active)
SELECT v.slug, v.name, c.id, v.signup_url,
       v.reward_desc, v.reward_desc_en, v.reward_desc_ja,
       v.countries::text[], v.allowed_code_types::text[], true
FROM (VALUES

-- ── 銀行信用卡（20）────────────────────────────────────────────────
('capital-one', 'Capital One', '銀行信用卡', 'https://www.capitalone.com/',
 '推薦好友核卡，雙方各得現金回饋或哩程獎勵',
 'Refer a friend who gets approved; both earn cash back or miles',
 '友達がカード発行で、双方にキャッシュバックまたはマイル', '{US}', '{referral}'), -- 榜 32
('chime', 'Chime', '銀行信用卡', 'https://www.chime.com/',
 '好友完成合格直接存款後，雙方各得 100 美元',
 'Both get $100 after your friend sets up a qualifying direct deposit',
 '友達が条件を満たす給与振込を設定で、双方に100ドル', '{US}', '{referral}'),
('cash-app', 'Cash App', '銀行信用卡', 'https://cash.app/',
 '好友用邀請碼註冊並完成首次轉帳，雙方各得 5 至 20 美元',
 'Both get $5-$20 when your friend signs up with your code and sends their first payment',
 '友達が招待コードで登録し初回送金すると、双方に5〜20ドル', '{US}', '{referral}'), -- 榜 44
('venmo', 'Venmo', '銀行信用卡', 'https://venmo.com/',
 '邀請好友完成首次付款，雙方各得現金獎勵',
 'Invite a friend; both earn cash after their first payment',
 '友達を招待し初回決済で、双方に現金特典', '{US}', '{referral}'), -- 榜 55
('paypal', 'PayPal', '銀行信用卡', 'https://www.paypal.com/',
 '推薦好友完成首筆合格交易可得現金，另有商家折扣碼',
 'Cash reward when a referred friend completes a qualifying transaction; merchant promo codes too',
 '紹介した友達が条件を満たす取引で現金特典、店舗クーポンも', '{}', '{referral,discount}'), -- 榜 43
('sofi', 'SoFi', '銀行信用卡', 'https://www.sofi.com/',
 '推薦好友開戶，雙方各得現金獎勵，金額依產品而異',
 'Both earn a cash bonus when a friend opens an account; amount varies by product',
 '友達の口座開設で双方に現金ボーナス、金額は商品により異なる', '{US}', '{referral}'),
('varo', 'Varo Bank', '銀行信用卡', 'https://www.varomoney.com/',
 '好友開戶並完成直接存款，雙方各得現金',
 'Both get cash when your friend opens an account and receives a direct deposit',
 '友達が口座開設と給与振込を完了で、双方に現金', '{US}', '{referral}'),
('current', 'Current', '銀行信用卡', 'https://current.com/',
 '推薦好友開戶，雙方各得 50 美元',
 'Both get $50 when your friend opens an account',
 '友達の口座開設で双方に50ドル', '{US}', '{referral}'),
('chase', 'Chase', '銀行信用卡', 'https://www.chase.com/',
 '信用卡 Refer-a-Friend，每位成功核卡可得紅利點數，年度有上限',
 'Credit card Refer-a-Friend: bonus points per approval, capped annually',
 'クレジットカードの友達紹介、承認ごとにボーナスポイント（年間上限あり）', '{US}', '{referral}'),
('american-express', 'American Express', '銀行信用卡', 'https://www.americanexpress.com/',
 '推薦好友申辦，可得 Membership Rewards 點數或現金回饋',
 'Refer a friend to earn Membership Rewards points or statement credit',
 '友達紹介でメンバーシップ・リワードポイントまたはキャッシュバック', '{US}', '{referral}'),
('discover', 'Discover', '銀行信用卡', 'https://www.discover.com/',
 '推薦好友申辦信用卡，雙方各得現金回饋',
 'Both earn cash back when a referred friend is approved for a card',
 '友達がカード発行で双方にキャッシュバック', '{US}', '{referral}'),
('citi', 'Citi', '銀行信用卡', 'https://www.citi.com/',
 '信用卡推薦好友可得 ThankYou 點數',
 'Earn ThankYou points for referring friends to a Citi card',
 'カード紹介でThankYouポイント', '{US}', '{referral}'),
('wells-fargo', 'Wells Fargo', '銀行信用卡', 'https://www.wellsfargo.com/',
 '帳戶與信用卡推薦獎勵，依當期方案給付',
 'Account and card referral bonuses, varies by current offer',
 '口座・カードの紹介特典（時期により変動）', '{US}', '{referral}'),
('bank-of-america', 'Bank of America', '銀行信用卡', 'https://www.bankofamerica.com/',
 '推薦好友開戶，推薦人得現金獎勵',
 'Cash bonus for the referrer when a friend opens an account',
 '友達の口座開設で紹介者に現金ボーナス', '{US}', '{referral}'),
('ally-bank', 'Ally Bank', '銀行信用卡', 'https://www.ally.com/',
 '開戶優惠碼與帳戶推薦獎勵',
 'Account opening promo codes and referral bonuses',
 '口座開設プロモコードと紹介特典', '{US}', '{referral,discount}'),
('revolut', 'Revolut', '銀行信用卡', 'https://www.revolut.com/',
 '推薦好友完成開卡與首次消費，雙方各得現金',
 'Both get cash when a friend orders a card and makes a first purchase',
 '友達がカード発行と初回利用で双方に現金', '{}', '{referral}'),
('wise', 'Wise', '銀行信用卡', 'https://wise.com/',
 '推薦 3 位好友各匯 200 英鎊以上可得約 75 美元，好友首筆匯款免手續費',
 'About $75 for 3 friends each transferring £200+; friends get a fee-free first transfer',
 '3人の友達が各200ポンド以上送金で約75ドル、友達は初回送金手数料無料', '{}', '{referral}'),
('dave', 'Dave', '銀行信用卡', 'https://dave.com/',
 '推薦好友開戶，雙方各得現金獎勵',
 'Both earn a cash bonus for a friend signup',
 '友達の登録で双方に現金ボーナス', '{US}', '{referral}'),
('moneylion', 'MoneyLion', '銀行信用卡', 'https://www.moneylion.com/',
 '推薦好友完成開戶，雙方各得現金',
 'Both get cash when a referred friend completes signup',
 '友達の登録完了で双方に現金', '{US}', '{referral}'),
('albert', 'Albert', '銀行信用卡', 'https://albert.com/',
 '推薦好友開戶，雙方各得 25 美元',
 'Both get $25 for a friend signup',
 '友達の登録で双方に25ドル', '{US}', '{referral}'),

-- ── 券商投資（18）────────────────────────────────────────────────
('robinhood', 'Robinhood', '券商投資', 'https://robinhood.com/',
 '推薦好友開戶，雙方各得一股隨機股票',
 'Both get a free random stock when a friend opens an account',
 '友達の口座開設で双方にランダムな株式1株', '{US}', '{referral}'),
('coinbase', 'Coinbase', '券商投資', 'https://www.coinbase.com/',
 '好友完成首筆 100 美元交易，雙方各得加密貨幣',
 'Both get crypto when your friend trades $100',
 '友達が100ドル取引で双方に暗号資産', '{}', '{referral}'),
('webull', 'Webull', '券商投資', 'https://www.webull.com/',
 '推薦好友開戶並入金，雙方各得免費股票',
 'Both get free stock when a friend opens and funds an account',
 '友達の口座開設と入金で双方に無料株', '{US}', '{referral}'),
('public', 'Public', '券商投資', 'https://public.com/',
 '推薦好友開戶，雙方各得股票獎勵',
 'Both get a stock reward for a friend signup',
 '友達の登録で双方に株式特典', '{US}', '{referral}'),
('acorns', 'Acorns', '券商投資', 'https://www.acorns.com/',
 '推薦好友開始投資，雙方各得 5 至 20 美元',
 'Both get $5-$20 when a friend starts investing',
 '友達が投資開始で双方に5〜20ドル', '{US}', '{referral}'),
('stash', 'Stash', '券商投資', 'https://www.stash.com/',
 '推薦好友開戶，雙方各得投資獎勵金',
 'Both get investment bonus cash for a friend signup',
 '友達の登録で双方に投資ボーナス', '{US}', '{referral}'),
('m1-finance', 'M1 Finance', '券商投資', 'https://m1.com/',
 '推薦好友開戶並入金，雙方各得現金',
 'Both get cash when a friend opens and funds an account',
 '友達の口座開設と入金で双方に現金', '{US}', '{referral}'),
('etoro', 'eToro', '券商投資', 'https://www.etoro.com/',
 '推薦好友入金交易，雙方各得現金獎勵',
 'Both get a cash bonus when a friend deposits and trades',
 '友達の入金・取引で双方に現金ボーナス', '{}', '{referral}'),
('kraken', 'Kraken', '券商投資', 'https://www.kraken.com/',
 '推薦好友完成交易，雙方各得加密貨幣',
 'Both get crypto when a referred friend trades',
 '友達の取引完了で双方に暗号資産', '{}', '{referral}'),
('gemini', 'Gemini', '券商投資', 'https://www.gemini.com/',
 '好友交易滿 100 美元，雙方各得等值 10 美元的比特幣',
 'Both get $10 in BTC when your friend trades $100',
 '友達が100ドル取引で双方に10ドル相当のBTC', '{}', '{referral}'),
('crypto-com', 'Crypto.com', '券商投資', 'https://crypto.com/',
 '推薦獎勵最高價值 500 美元加密貨幣，依當期活動而定',
 'Referral rewards up to $500 in crypto, depending on the current campaign',
 '紹介特典は最大500ドル相当の暗号資産（時期により変動）', '{}', '{referral}'),
('binance-us', 'Binance.US', '券商投資', 'https://www.binance.us/',
 '推薦好友交易可分潤手續費',
 'Earn a share of trading fees from referred friends',
 '紹介した友達の取引手数料の一部を還元', '{US}', '{referral}'),
('charles-schwab', 'Charles Schwab', '券商投資', 'https://www.schwab.com/',
 '推薦好友開戶，雙方各得現金獎勵，依入金金額分級',
 'Both get a cash bonus tiered by the friend deposit amount',
 '友達の口座開設で双方に現金ボーナス（入金額により段階制）', '{US}', '{referral}'),
('moomoo', 'moomoo', '券商投資', 'https://www.moomoo.com/',
 '開戶入金送股票，推薦好友另有獎勵',
 'Free stock for funding an account, plus separate referral rewards',
 '口座開設・入金で株式プレゼント、紹介特典は別途', '{}', '{referral}'),
('betterment', 'Betterment', '券商投資', 'https://www.betterment.com/',
 '推薦好友開戶，雙方各得免管理費期間',
 'Both get a period of waived management fees for a friend signup',
 '友達の口座開設で双方に管理手数料無料期間', '{US}', '{referral}'),
('wealthfront', 'Wealthfront', '券商投資', 'https://www.wealthfront.com/',
 '推薦好友開戶，雙方各得 5,000 美元免管理費額度',
 'Both get $5,000 managed free for a friend signup',
 '友達の口座開設で双方に5,000ドル分の管理手数料無料枠', '{US}', '{referral}'),
('fundrise', 'Fundrise', '券商投資', 'https://fundrise.com/',
 '推薦好友投資，雙方各得免管理費期間',
 'Both get waived advisory fees when a friend invests',
 '友達の投資開始で双方に手数料無料期間', '{US}', '{referral}'),
('kalshi', 'Kalshi', '券商投資', 'https://kalshi.com/',
 '推薦好友開戶交易，雙方各得交易金',
 'Both get trading credit when a referred friend trades',
 '友達の口座開設・取引で双方に取引クレジット', '{US}', '{referral}'), -- 榜 66

-- ── 外送（24）──────────────────────────────────────────────────
('doordash', 'DoorDash', '外送', 'https://www.doordash.com/',
 '新用戶首單滿 15 美元享 5 折，另有好友推薦雙向折扣',
 'New users get 50% off a first order of $15+; two-sided referral discounts too',
 '新規は15ドル以上の初回注文が50%オフ、友達紹介の双方割引もあり', '{US}', '{referral,discount}'), -- 榜 18
('uber-eats', 'Uber Eats', '外送', 'https://www.ubereats.com/',
 '好友用推薦碼首單滿 25 美元折 20 美元，推薦人得 10 美元折扣碼',
 'Friend gets $20 off a first order of $25+; referrer gets a $10 coupon',
 '友達は25ドル以上の初回注文で20ドルオフ、紹介者は10ドルクーポン', '{}', '{referral,discount}'), -- 榜 77
('instacart', 'Instacart', '外送', 'https://www.instacart.com/',
 '新用戶首單得 10 美元購物金，另有好友推薦折扣',
 'New users get $10 credit on a first order, plus referral discounts',
 '新規は初回注文に10ドルクレジット、友達紹介割引もあり', '{US}', '{referral,discount}'),
('grubhub', 'Grubhub', '外送', 'https://www.grubhub.com/',
 '新用戶首單折 10 美元無低消，推薦好友另有回饋',
 'New users get $10 off a first order with no minimum; referral credits too',
 '新規は初回注文10ドルオフ（最低金額なし）、紹介特典もあり', '{US}', '{referral,discount}'),
('gopuff', 'Gopuff', '外送', 'https://www.gopuff.com/',
 '推薦好友完成首單，雙方各得訂單折扣',
 'Both get order credit when a friend places a first order',
 '友達の初回注文で双方に注文割引', '{US}', '{referral,discount}'),
('shipt', 'Shipt', '外送', 'https://www.shipt.com/',
 '推薦好友加入會員，雙方各得會員折扣',
 'Both get membership credit for a friend signup',
 '友達の会員登録で双方に会員クレジット', '{US}', '{referral}'),
('caviar', 'Caviar', '外送', 'https://www.trycaviar.com/',
 '新用戶首單折扣碼',
 'First-order promo codes for new users',
 '新規向け初回注文プロモコード', '{US}', '{discount}'),
('chipotle', 'Chipotle', '外送', 'https://www.chipotle.com/',
 'App 訂餐折扣碼與 Rewards 好友推薦獎勵',
 'App order promo codes and Rewards referral bonuses',
 'アプリ注文のプロモコードとリワード友達紹介特典', '{US}', '{referral,discount}'), -- 榜 35
('mcdonalds', 'McDonald''s', '外送', 'https://www.mcdonalds.com/',
 'App 專屬折價券與限時優惠碼',
 'App-exclusive coupons and limited-time promo codes',
 'アプリ限定クーポンと期間限定プロモコード', '{}', '{discount}'), -- 榜 63
('taco-bell', 'Taco Bell', '外送', 'https://www.tacobell.com/',
 'App 訂餐折扣碼與會員獎勵',
 'App order promo codes and rewards offers',
 'アプリ注文プロモコードと会員特典', '{US}', '{discount}'), -- 榜 82
('dominos', 'Domino''s Pizza', '外送', 'https://www.dominos.com/',
 '線上訂餐 promo code 與會員推薦優惠',
 'Online ordering promo codes and rewards referral offers',
 'オンライン注文プロモコードと会員紹介特典', '{US}', '{discount}'), -- 榜 99
('starbucks', 'Starbucks', '外送', 'https://www.starbucks.com/',
 'Rewards 好友推薦與 App 專屬優惠碼',
 'Rewards friend referrals and app-exclusive offer codes',
 'リワード友達紹介とアプリ限定クーポン', '{US}', '{referral,discount}'),
('dunkin', 'Dunkin''', '外送', 'https://www.dunkindonuts.com/',
 'App 專屬優惠與好友推薦獎勵',
 'App-exclusive offers and friend referral bonuses',
 'アプリ限定オファーと友達紹介特典', '{US}', '{referral,discount}'),
('chick-fil-a', 'Chick-fil-A', '外送', 'https://www.chick-fil-a.com/',
 'App 會員獎勵與限時優惠碼',
 'App rewards and limited-time offer codes',
 'アプリ会員特典と期間限定クーポン', '{US}', '{discount}'),
('panera', 'Panera Bread', '外送', 'https://www.panerabread.com/',
 'Unlimited Sip Club 推薦與訂餐優惠碼',
 'Unlimited Sip Club referrals and order promo codes',
 'Unlimited Sip Clubの紹介と注文クーポン', '{US}', '{referral,discount}'),
('wendys', 'Wendy''s', '外送', 'https://www.wendys.com/',
 'App 優惠券與訂餐折扣碼',
 'App coupons and order promo codes',
 'アプリクーポンと注文プロモコード', '{US}', '{discount}'),
('burger-king', 'Burger King', '外送', 'https://www.bk.com/',
 'App 折價券與限時優惠碼',
 'App coupons and limited-time offer codes',
 'アプリクーポンと期間限定コード', '{US}', '{discount}'),
('papa-johns', 'Papa Johns', '外送', 'https://www.papajohns.com/',
 '線上訂餐 promo code',
 'Online ordering promo codes',
 'オンライン注文プロモコード', '{US}', '{discount}'),
('subway', 'Subway', '外送', 'https://www.subway.com/',
 'App 與線上訂餐優惠碼',
 'App and online ordering promo codes',
 'アプリ・オンライン注文クーポン', '{US}', '{discount}'),
('seven-brew-coffee', '7 Brew Coffee', '外送', 'https://7brew.com/',
 'App 會員獎勵與好友推薦優惠',
 'App rewards and friend referral offers',
 'アプリ会員特典と友達紹介オファー', '{US}', '{referral,discount}'), -- 榜 2
('hellofresh', 'HelloFresh', '外送', 'https://www.hellofresh.com/',
 '推薦好友訂購，雙方各得餐盒折扣，首箱常有大幅折扣碼',
 'Both get box credit for a referral; heavy first-box promo codes are common',
 '友達紹介で双方にボックス割引、初回は大幅割引コードが多い', '{US}', '{referral,discount}'),
('blue-apron', 'Blue Apron', '外送', 'https://www.blueapron.com/',
 '推薦好友可送免費餐盒，另有首購折扣碼',
 'Send a friend a free box; first-order promo codes too',
 '友達に無料ボックスを贈れる、初回割引コードもあり', '{US}', '{referral,discount}'),
('factor', 'Factor', '外送', 'https://www.factor75.com/',
 '首購折扣碼與好友推薦獎勵',
 'First-order promo codes and friend referral rewards',
 '初回割引コードと友達紹介特典', '{US}', '{referral,discount}'),
('home-chef', 'Home Chef', '外送', 'https://www.homechef.com/',
 '推薦好友訂購，雙方各得 35 美元折扣',
 'Both get $35 off when a friend subscribes',
 '友達の申込で双方に35ドルオフ', '{US}', '{referral,discount}'),

-- ── 影音串流（12）───────────────────────────────────────────────
('spotify', 'Spotify', '影音串流', 'https://www.spotify.com/',
 'Premium 首購優惠碼與家庭方案邀請',
 'Premium first-purchase promo codes and family plan invites',
 'Premium初回プロモコードとファミリープラン招待', '{}', '{discount}'), -- 榜 32
('hulu', 'Hulu', '影音串流', 'https://www.hulu.com/',
 '新訂戶優惠碼與限時方案折扣',
 'New subscriber promo codes and limited-time plan discounts',
 '新規向けプロモコードと期間限定プラン割引', '{US}', '{discount}'),
('disney-plus', 'Disney+', '影音串流', 'https://www.disneyplus.com/',
 '新訂戶促銷碼與 Bundle 組合折扣',
 'New subscriber promo codes and bundle discounts',
 '新規プロモコードとバンドル割引', '{}', '{discount}'), -- 榜 64
('hbo-max', 'HBO Max', '影音串流', 'https://www.hbomax.com/',
 '新訂戶折扣碼與年繳優惠',
 'New subscriber promo codes and annual plan discounts',
 '新規プロモコードと年額プラン割引', '{}', '{discount}'), -- 榜 95
('paramount-plus', 'Paramount+', '影音串流', 'https://www.paramountplus.com/',
 '免費試用碼與訂閱折扣碼',
 'Free trial codes and subscription promo codes',
 '無料トライアルコードとサブスク割引コード', '{}', '{discount}'), -- 榜 83
('peacock', 'Peacock', '影音串流', 'https://www.peacocktv.com/',
 '訂閱折扣碼與限時方案優惠',
 'Subscription promo codes and limited-time plan offers',
 'サブスク割引コードと期間限定オファー', '{US}', '{discount}'),
('sling-tv', 'Sling TV', '影音串流', 'https://www.sling.com/',
 '推薦好友訂閱，雙方各得帳單折抵',
 'Both get bill credit when a friend subscribes',
 '友達の加入で双方に請求クレジット', '{US}', '{referral,discount}'),
('fubo', 'Fubo', '影音串流', 'https://www.fubo.tv/',
 '推薦好友訂閱，雙方各得帳單折抵',
 'Both get bill credit for a friend subscription',
 '友達の加入で双方に請求クレジット', '{US}', '{referral,discount}'),
('philo', 'Philo', '影音串流', 'https://www.philo.com/',
 '推薦好友訂閱，雙方各得免費月份',
 'Both get a free month when a friend subscribes',
 '友達の加入で双方に1ヶ月無料', '{US}', '{referral}'),
('siriusxm', 'SiriusXM', '影音串流', 'https://www.siriusxm.com/',
 '推薦好友訂閱，雙方各得免費收聽期',
 'Both get free listening time for a friend subscription',
 '友達の加入で双方に無料視聴期間', '{US}', '{referral}'),
('audible', 'Audible', '影音串流', 'https://www.audible.com/',
 '推薦好友加入，雙方各得有聲書額度',
 'Both get audiobook credits for a friend signup',
 '友達の登録で双方にオーディオブッククレジット', '{}', '{referral}'),
('crunchyroll', 'Crunchyroll', '影音串流', 'https://www.crunchyroll.com/',
 '訂閱折扣碼與好友邀請獎勵',
 'Subscription promo codes and friend invite rewards',
 'サブスク割引コードと友達招待特典', '{}', '{referral,discount}'),

-- ── 電信通訊（12）───────────────────────────────────────────────
('t-mobile', 'T-Mobile', '電信通訊', 'https://www.t-mobile.com/',
 '推薦好友辦門號，雙方各得帳單折抵',
 'Both get bill credit when a friend activates a line',
 '友達の回線契約で双方に請求クレジット', '{US}', '{referral}'), -- 榜 71（T-Life）
('mint-mobile', 'Mint Mobile', '電信通訊', 'https://www.mintmobile.com/refer-a-friend/',
 '推薦人得 45 美元續約金、好友得 15 美元，每年上限 4 次',
 'Referrer gets $45 renewal credit, friend gets $15; up to 4 per calendar year',
 '紹介者に45ドル、友達に15ドルの更新クレジット（年4回まで）', '{US}', '{referral}'),
('visible', 'Visible', '電信通訊', 'https://www.visible.com/',
 '推薦好友辦門號，雙方各得帳單折抵',
 'Both get bill credit for a friend activation',
 '友達の回線契約で双方に請求クレジット', '{US}', '{referral}'),
('google-fi', 'Google Fi', '電信通訊', 'https://fi.google.com/',
 '推薦好友辦門號，雙方各得約 60 美元帳單折抵',
 'Both get about $60 in bill credit for a friend activation',
 '友達の回線契約で双方に約60ドルの請求クレジット', '{US}', '{referral}'),
('us-mobile', 'US Mobile', '電信通訊', 'https://www.usmobile.com/',
 '推薦好友辦門號，雙方各得帳戶金',
 'Both get account credit for a friend activation',
 '友達の回線契約で双方にアカウントクレジット', '{US}', '{referral}'),
('verizon', 'Verizon', '電信通訊', 'https://www.verizon.com/',
 '推薦好友辦門號可得帳單折抵',
 'Bill credit for referring a friend who activates a line',
 '友達の回線契約紹介で請求クレジット', '{US}', '{referral}'),
('att', 'AT&T', '電信通訊', 'https://www.att.com/',
 '推薦好友辦門號可得帳單折抵',
 'Bill credit for referring a friend who activates a line',
 '友達の回線契約紹介で請求クレジット', '{US}', '{referral}'),
('boost-mobile', 'Boost Mobile', '電信通訊', 'https://www.boostmobile.com/',
 '推薦好友辦門號，雙方各得帳單折抵',
 'Both get bill credit for a friend activation',
 '友達の回線契約で双方に請求クレジット', '{US}', '{referral}'),
('cricket-wireless', 'Cricket Wireless', '電信通訊', 'https://www.cricketwireless.com/',
 '推薦好友辦門號，雙方各得帳單折抵',
 'Both get bill credit for a friend activation',
 '友達の回線契約で双方に請求クレジット', '{US}', '{referral}'),
('tello', 'Tello', '電信通訊', 'https://tello.com/',
 '推薦好友辦門號，雙方各得 10 美元帳戶金',
 'Both get $10 account credit for a friend activation',
 '友達の回線契約で双方に10ドルのアカウントクレジット', '{US}', '{referral}'),
('xfinity-mobile', 'Xfinity Mobile', '電信通訊', 'https://www.xfinity.com/mobile',
 '推薦好友辦門號可得帳單折抵',
 'Bill credit for a friend activation',
 '友達の回線契約で請求クレジット', '{US}', '{referral}'),
('metro-by-t-mobile', 'Metro by T-Mobile', '電信通訊', 'https://www.metrobyt-mobile.com/',
 '推薦好友辦門號，雙方各得帳單折抵',
 'Both get bill credit for a friend activation',
 '友達の回線契約で双方に請求クレジット', '{US}', '{referral}'),

-- ── 旅遊訂房（16）───────────────────────────────────────────────
-- Airbnb 的旅客推薦在美國已經停掉了（只剩中國、義大利、日本、墨西哥），
-- 現在美國能推的只有房東。這條要寫清楚，不然使用者會投一堆早就失效的旅客邀請碼。
('airbnb', 'Airbnb', '旅遊訂房', 'https://www.airbnb.com/refer',
 '推薦新房東完成首次接待可得現金獎勵；美國目前沒有旅客推薦方案',
 'Cash reward for referring a new host who completes a first booking; no guest referral program in the US',
 '新規ホストの紹介で初回予約完了時に現金特典（米国にゲスト紹介制度はなし）', '{}', '{referral}'), -- 榜 78
('booking-com', 'Booking.com', '旅遊訂房', 'https://www.booking.com/',
 '推薦好友完成首次入住，雙方各得現金回饋',
 'Both get cash back when a friend completes a first stay',
 '友達の初回宿泊完了で双方にキャッシュバック', '{}', '{referral,discount}'),
('vrbo', 'Vrbo', '旅遊訂房', 'https://www.vrbo.com/',
 '訂房折扣碼與限時優惠',
 'Booking promo codes and limited-time offers',
 '予約割引コードと期間限定オファー', '{}', '{discount}'),
('expedia', 'Expedia', '旅遊訂房', 'https://www.expedia.com/',
 '會員折扣碼與好友推薦獎勵',
 'Member promo codes and friend referral rewards',
 '会員割引コードと友達紹介特典', '{}', '{referral,discount}'),
('hopper', 'Hopper', '旅遊訂房', 'https://hopper.com/',
 '推薦好友訂票訂房，雙方各得 Carrot Cash',
 'Both earn Carrot Cash when a friend books',
 '友達の予約で双方にCarrot Cash', '{}', '{referral}'),
('hotels-com', 'Hotels.com', '旅遊訂房', 'https://www.hotels.com/',
 '訂房折扣碼與會員優惠',
 'Booking promo codes and member offers',
 '予約割引コードと会員特典', '{}', '{discount}'),
('marriott-bonvoy', 'Marriott Bonvoy', '旅遊訂房', 'https://www.marriott.com/',
 '推薦好友入住可得 Bonvoy 點數',
 'Earn Bonvoy points for referring a friend who stays',
 '友達の宿泊紹介でBonvoyポイント', '{}', '{referral}'),
('hilton-honors', 'Hilton Honors', '旅遊訂房', 'https://www.hilton.com/',
 '推薦好友入住可得 Honors 點數',
 'Earn Honors points for referring a friend who stays',
 '友達の宿泊紹介でHonorsポイント', '{}', '{referral}'),
('ihg-one-rewards', 'IHG One Rewards', '旅遊訂房', 'https://www.ihg.com/',
 '推薦好友入住可得點數，另有訂房折扣碼',
 'Points for referring a friend who stays, plus booking promo codes',
 '友達の宿泊紹介でポイント、予約割引コードもあり', '{}', '{referral,discount}'),
('turo', 'Turo', '旅遊訂房', 'https://turo.com/us/en/car-rental/united-states/refer-a-host',
 '推薦新車主成功上架出租，雙方各得 300 美元',
 'Both get $300 when a referred host successfully starts hosting',
 '紹介したホストが出品開始で双方に300ドル', '{US}', '{referral}'),
('getaround', 'Getaround', '旅遊訂房', 'https://www.getaround.com/',
 '推薦好友完成首次租車，雙方各得行程折抵',
 'Both get trip credit for a friend first rental',
 '友達の初回レンタルで双方に利用クレジット', '{US}', '{referral}'),
('southwest', 'Southwest Airlines', '旅遊訂房', 'https://www.southwest.com/',
 'Rapid Rewards 好友推薦與訂票促銷碼',
 'Rapid Rewards referrals and booking promo codes',
 'Rapid Rewards友達紹介と予約プロモコード', '{US}', '{referral,discount}'),
('delta', 'Delta Air Lines', '旅遊訂房', 'https://www.delta.com/',
 'SkyMiles 推薦獎勵與訂票促銷碼',
 'SkyMiles referral rewards and booking promo codes',
 'SkyMiles紹介特典と予約プロモコード', '{US}', '{referral,discount}'),
('jetblue', 'JetBlue', '旅遊訂房', 'https://www.jetblue.com/',
 'TrueBlue 推薦好友，雙方各得點數',
 'Both earn TrueBlue points for a friend referral',
 'TrueBlue友達紹介で双方にポイント', '{US}', '{referral}'),
('priceline', 'Priceline', '旅遊訂房', 'https://www.priceline.com/',
 '訂房與機票 promo code',
 'Hotel and flight promo codes',
 'ホテル・航空券のプロモコード', '{US}', '{discount}'),
('klook', 'Klook', '旅遊訂房', 'https://www.klook.com/',
 '推薦好友完成首次訂購，雙方各得 Klook Credit',
 'Both get Klook Credits when a friend completes a first booking',
 '友達の初回予約で双方にKlookクレジット', '{}', '{referral,discount}'),

-- ── 購物電商（28）───────────────────────────────────────────────
('temu', 'Temu', '購物電商', 'https://www.temu.com/',
 '邀請好友下載可得現金與折價券',
 'Cash and coupons for inviting friends to download',
 '友達招待でキャッシュとクーポン', '{}', '{referral,discount}'), -- 榜 10
('shein', 'SHEIN', '購物電商', 'https://www.shein.com/',
 '邀請好友註冊，雙方各得積分與折價券',
 'Both get points and coupons for a friend signup',
 '友達の登録で双方にポイントとクーポン', '{}', '{referral,discount}'), -- 榜 54
('amazon', 'Amazon Shopping', '購物電商', 'https://www.amazon.com/',
 'Prime 推薦優惠與商品折扣碼',
 'Prime referral offers and product promo codes',
 'Prime紹介特典と商品プロモコード', '{}', '{discount}'), -- 榜 51
('walmart', 'Walmart', '購物電商', 'https://www.walmart.com/',
 'Walmart+ 推薦好友，雙方各得回饋與購物折扣碼',
 'Walmart+ referrals with two-sided credit, plus store promo codes',
 'Walmart+の友達紹介で双方に特典、店舗クーポンもあり', '{US}', '{referral,discount}'), -- 榜 26
('target', 'Target', '購物電商', 'https://www.target.com/',
 'Circle 會員優惠與商品折扣碼',
 'Circle member offers and product promo codes',
 'Circle会員特典と商品クーポン', '{US}', '{discount}'), -- 榜 79
('costco', 'Costco', '購物電商', 'https://www.costco.com/',
 '推薦好友入會，雙方各得購物金',
 'Both get shop credit for a friend membership signup',
 '友達の入会で双方にショップクレジット', '{US}', '{referral}'), -- 榜 74
('ebay', 'eBay', '購物電商', 'https://www.ebay.com/',
 '購物折扣碼與賣家推薦獎勵',
 'Shopping promo codes and seller referral rewards',
 '買い物クーポンと出品者紹介特典', '{}', '{referral,discount}'), -- 榜 98
('aliexpress', 'AliExpress', '購物電商', 'https://www.aliexpress.com/',
 '邀請好友註冊，雙方各得優惠券',
 'Both get coupons for a friend signup',
 '友達の登録で双方にクーポン', '{}', '{referral,discount}'), -- 榜 42
('vinted', 'Vinted', '購物電商', 'https://www.vinted.com/',
 '推薦好友完成首購，雙方各得購物金',
 'Both get credit when a friend makes a first purchase',
 '友達の初回購入で双方にクレジット', '{}', '{referral}'), -- 榜 5
('depop', 'Depop', '購物電商', 'https://www.depop.com/',
 '推薦好友註冊，雙方各得購物金與折扣碼',
 'Both get shopping credit and promo codes for a friend signup',
 '友達の登録で双方にクレジットとクーポン', '{}', '{referral,discount}'), -- 榜 7
('whatnot', 'Whatnot', '購物電商', 'https://www.whatnot.com/',
 '推薦好友完成首購，雙方各得 15 美元購物金',
 'Both get $15 credit when a friend makes a first purchase',
 '友達の初回購入で双方に15ドルクレジット', '{US}', '{referral}'), -- 榜 27
('poshmark', 'Poshmark', '購物電商', 'https://poshmark.com/',
 '用推薦碼註冊，雙方各得 10 美元購物金',
 'Both get $10 credit when signing up with a referral code',
 '紹介コードでの登録で双方に10ドルクレジット', '{US}', '{referral}'),
('mercari', 'Mercari', '購物電商', 'https://www.mercari.com/',
 '用邀請碼註冊，雙方各得購物金',
 'Both get credit when signing up with an invite code',
 '招待コードでの登録で双方にクレジット', '{US}', '{referral}'),
('rakuten', 'Rakuten', '購物電商', 'https://www.rakuten.com/',
 '推薦好友完成合格消費，最高可得 50 美元獎金',
 'Up to $50 bonus when a referred friend makes a qualifying purchase',
 '紹介した友達の条件達成で最大50ドルのボーナス', '{US}', '{referral}'),
('ibotta', 'Ibotta', '購物電商', 'https://ibotta.com/',
 '好友七天內上傳首張收據，可得 7 至 10 美元獎金',
 'Earn $7-$10 when a friend submits a first receipt within seven days',
 '友達が7日以内に初回レシートを提出で7〜10ドル', '{US}', '{referral}'),
('fetch', 'Fetch', '購物電商', 'https://www.fetch.com/',
 '用推薦碼註冊，雙方各得點數',
 'Both get points when signing up with a referral code',
 '紹介コードでの登録で双方にポイント', '{US}', '{referral}'),
('honey', 'Honey', '購物電商', 'https://www.joinhoney.com/',
 '推薦好友可得 Gold 點數，另有自動套用的商店折扣碼',
 'Gold points for referrals, plus auto-applied store coupon codes',
 '紹介でGoldポイント、店舗クーポンの自動適用もあり', '{}', '{referral,discount}'),
('capital-one-shopping', 'Capital One Shopping', '購物電商', 'https://capitaloneshopping.com/',
 '推薦好友安裝使用，雙方各得購物金',
 'Both get credit when a friend installs and shops',
 '友達のインストール・利用で双方にクレジット', '{US}', '{referral}'), -- 榜 81
('shop-app', 'Shop', '購物電商', 'https://shop.app/',
 'Shop Pay 商店折扣碼與首購優惠',
 'Shop Pay store promo codes and first-purchase offers',
 'Shop Pay店舗クーポンと初回特典', '{}', '{discount}'), -- 榜 39
('wayfair', 'Wayfair', '購物電商', 'https://www.wayfair.com/',
 '推薦好友首購，雙方各得購物金，另有站上折扣碼',
 'Both get credit on a friend first purchase, plus site promo codes',
 '友達の初回購入で双方にクレジット、サイトクーポンもあり', '{US}', '{referral,discount}'),
('chewy', 'Chewy', '購物電商', 'https://www.chewy.com/',
 '推薦好友首購，雙方各得 20 美元電子禮卡',
 'Both get a $20 e-gift card on a friend first order',
 '友達の初回購入で双方に20ドルのeギフトカード', '{US}', '{referral,discount}'),
('etsy', 'Etsy', '購物電商', 'https://www.etsy.com/',
 '賣家推薦獎勵與賣場折扣碼',
 'Seller referral rewards and shop coupon codes',
 '出品者紹介特典とショップクーポン', '{}', '{referral,discount}'),
('lowes', 'Lowe''s', '購物電商', 'https://www.lowes.com/',
 'MyLowes Rewards 會員折扣碼',
 'MyLowes Rewards member promo codes',
 'MyLowes Rewards会員クーポン', '{US}', '{discount}'), -- 榜 76
('home-depot', 'The Home Depot', '購物電商', 'https://www.homedepot.com/',
 '線上訂單折扣碼與會員優惠',
 'Online order promo codes and member offers',
 'オンライン注文クーポンと会員特典', '{US}', '{discount}'),
('thrive-market', 'Thrive Market', '購物電商', 'https://thrivemarket.com/',
 '推薦好友入會，雙方各得 40 美元購物金',
 'Both get $40 credit for a friend membership',
 '友達の入会で双方に40ドルクレジット', '{US}', '{referral,discount}'),
('stockx', 'StockX', '購物電商', 'https://stockx.com/',
 '推薦好友首購，雙方各得購物折扣',
 'Both get a discount on a friend first purchase',
 '友達の初回購入で双方に割引', '{}', '{referral,discount}'),
('swagbucks', 'Swagbucks', '購物電商', 'https://www.swagbucks.com/',
 '推薦好友可分潤其收益的 10%',
 'Earn 10% of what referred friends earn',
 '紹介した友達の獲得額の10%を還元', '{US}', '{referral}'),
('freecash', 'Freecash', '購物電商', 'https://freecash.com/',
 '推薦好友可分潤其收益',
 'Earn a share of what referred friends earn',
 '紹介した友達の獲得額の一部を還元', '{}', '{referral}'), -- 榜 40

-- ── 交通出行（8）────────────────────────────────────────────────
('uber', 'Uber', '交通出行', 'https://www.uber.com/',
 '推薦好友完成首程，雙方各得乘車折扣',
 'Both get ride credit when a friend takes a first trip',
 '友達の初回乗車で双方に乗車クレジット', '{}', '{referral,discount}'), -- 榜 14
('lyft', 'Lyft', '交通出行', 'https://www.lyft.com/',
 '推薦好友完成首程，雙方各得乘車折抵',
 'Both get ride credit for a friend first ride',
 '友達の初回乗車で双方に乗車クレジット', '{US}', '{referral,discount}'), -- 榜 30
('bird', 'Bird', '交通出行', 'https://www.bird.co/',
 '推薦好友註冊，雙方各得騎乘金',
 'Both get ride credit for a friend signup',
 '友達の登録で双方にライドクレジット', '{}', '{referral}'),
('lime', 'Lime', '交通出行', 'https://www.li.me/',
 '推薦好友完成首次騎乘，雙方各得騎乘金',
 'Both get ride credit for a friend first ride',
 '友達の初回ライドで双方にクレジット', '{}', '{referral}'),
('revel', 'Revel', '交通出行', 'https://gorevel.com/',
 '推薦好友註冊，雙方各得乘車金',
 'Both get ride credit for a friend signup',
 '友達の登録で双方に乗車クレジット', '{US}', '{referral}'),
('zipcar', 'Zipcar', '交通出行', 'https://www.zipcar.com/',
 '推薦好友入會，雙方各得行車金，另有入會折扣碼',
 'Both get driving credit for a friend membership, plus signup promo codes',
 '友達の入会で双方にドライブクレジット、入会クーポンもあり', '{US}', '{referral,discount}'),
('curb', 'Curb', '交通出行', 'https://gocurb.com/',
 '推薦好友完成首程，雙方各得乘車折抵',
 'Both get ride credit for a friend first trip',
 '友達の初回乗車で双方に乗車クレジット', '{US}', '{referral}'),
('via', 'Via', '交通出行', 'https://ridewithvia.com/',
 '推薦好友註冊，雙方各得乘車金',
 'Both get ride credit for a friend signup',
 '友達の登録で双方に乗車クレジット', '{US}', '{referral}'),

-- ── 健康運動（12）───────────────────────────────────────────────
('strava', 'Strava', '健康運動', 'https://www.strava.com/',
 '訂閱推薦與免費試用折扣碼',
 'Subscription referrals and free trial promo codes',
 'サブスク紹介と無料トライアルコード', '{}', '{referral,discount}'), -- 榜 88
('whoop', 'WHOOP', '健康運動', 'https://www.whoop.com/',
 '推薦好友入會，雙方各得一個月免費會籍',
 'Both get a free month of membership for a friend signup',
 '友達の入会で双方に1ヶ月無料', '{}', '{referral}'),
('peloton', 'Peloton', '健康運動', 'https://www.onepeloton.com/',
 '推薦好友購買設備，雙方各得 100 美元配件金',
 'Both get $100 in accessory credit when a friend buys equipment',
 '友達の機器購入で双方に100ドルのアクセサリークレジット', '{US}', '{referral,discount}'),
('classpass', 'ClassPass', '健康運動', 'https://classpass.com/',
 '推薦好友加入，雙方各得課程 credits',
 'Both get class credits for a friend signup',
 '友達の登録で双方にクラスクレジット', '{}', '{referral}'),
('planet-fitness', 'Planet Fitness', '健康運動', 'https://www.planetfitness.com/',
 '入會優惠碼與帶友同行方案',
 'Membership promo codes and bring-a-friend offers',
 '入会クーポンと友達同伴プラン', '{US}', '{discount}'),
('noom', 'Noom', '健康運動', 'https://www.noom.com/',
 '推薦好友訂閱，雙方各得訂閱折扣',
 'Both get subscription credit for a friend signup',
 '友達の加入で双方にサブスク割引', '{US}', '{referral,discount}'),
('myfitnesspal', 'MyFitnessPal', '健康運動', 'https://www.myfitnesspal.com/',
 'Premium 訂閱折扣碼與好友邀請',
 'Premium subscription promo codes and friend invites',
 'Premiumサブスク割引コードと友達招待', '{}', '{referral,discount}'),
('calm', 'Calm', '健康運動', 'https://www.calm.com/',
 '訂閱折扣碼與好友邀請獎勵',
 'Subscription promo codes and friend invite rewards',
 'サブスク割引コードと友達招待特典', '{}', '{referral,discount}'),
('headspace', 'Headspace', '健康運動', 'https://www.headspace.com/',
 '推薦好友訂閱，雙方各得免費月份',
 'Both get a free month for a friend subscription',
 '友達の加入で双方に1ヶ月無料', '{}', '{referral,discount}'),
('hims-hers', 'Hims & Hers', '健康運動', 'https://www.forhims.com/',
 '推薦好友訂閱，雙方各得處方訂閱折扣',
 'Both get credit toward subscriptions for a friend signup',
 '友達の加入で双方にサブスク割引', '{US}', '{referral,discount}'),
('ro', 'Ro', '健康運動', 'https://ro.co/',
 '推薦好友使用服務，雙方各得服務折扣',
 'Both get service credit for a friend signup',
 '友達の利用開始で双方にサービスクレジット', '{US}', '{referral}'),
('oura', 'Oura', '健康運動', 'https://ouraring.com/',
 '推薦好友購買智慧戒指，雙方各得 40 美元折扣',
 'Both get $40 off when a friend buys a ring',
 '友達のリング購入で双方に40ドルオフ', '{}', '{referral,discount}'),

-- ── 學習教育（10）───────────────────────────────────────────────
('duolingo', 'Duolingo', '學習教育', 'https://www.duolingo.com/',
 '推薦好友，雙方各得 Super 免費使用期',
 'Both get free Super time for a friend signup',
 '友達紹介で双方にSuperの無料期間', '{}', '{referral}'), -- 榜 63
('babbel', 'Babbel', '學習教育', 'https://www.babbel.com/',
 '推薦好友訂閱，雙方各得訂閱折扣',
 'Both get subscription credit for a friend signup',
 '友達の加入で双方にサブスク割引', '{}', '{referral,discount}'),
('rosetta-stone', 'Rosetta Stone', '學習教育', 'https://www.rosettastone.com/',
 '終身方案與訂閱折扣碼',
 'Lifetime plan and subscription promo codes',
 '生涯プラン・サブスクの割引コード', '{}', '{discount}'),
('coursera', 'Coursera', '學習教育', 'https://www.coursera.org/',
 'Coursera Plus 推薦與課程折扣碼',
 'Coursera Plus referrals and course promo codes',
 'Coursera Plus紹介とコース割引コード', '{}', '{referral,discount}'),
('udemy', 'Udemy', '學習教育', 'https://www.udemy.com/',
 '課程折扣碼與好友推薦獎勵',
 'Course promo codes and friend referral rewards',
 'コース割引コードと友達紹介特典', '{}', '{referral,discount}'),
('skillshare', 'Skillshare', '學習教育', 'https://www.skillshare.com/',
 '推薦好友訂閱，雙方各得免費月份',
 'Both get a free month for a friend subscription',
 '友達の加入で双方に1ヶ月無料', '{}', '{referral}'),
('masterclass', 'MasterClass', '學習教育', 'https://www.masterclass.com/',
 '推薦好友訂閱，雙方各得訂閱優惠',
 'Both get subscription offers for a friend signup',
 '友達の加入で双方にサブスク特典', '{}', '{referral,discount}'),
('chegg', 'Chegg', '學習教育', 'https://www.chegg.com/',
 '推薦好友訂閱，雙方各得訂閱折抵',
 'Both get subscription credit for a friend signup',
 '友達の加入で双方にサブスククレジット', '{US}', '{referral,discount}'),
('brilliant', 'Brilliant', '學習教育', 'https://brilliant.org/',
 '推薦好友訂閱，雙方各得免費月份與年繳折扣',
 'Both get a free month plus annual plan discounts',
 '友達の加入で双方に1ヶ月無料と年額割引', '{}', '{referral,discount}'),
('preply', 'Preply', '學習教育', 'https://preply.com/',
 '推薦好友購課，雙方各得課程金',
 'Both get lesson credit when a friend buys lessons',
 '友達のレッスン購入で双方にクレジット', '{}', '{referral,discount}'),

-- ── 軟體訂閱（20）───────────────────────────────────────────────
('dropbox', 'Dropbox', '軟體訂閱', 'https://www.dropbox.com/',
 '每推薦一位好友得 500MB 空間，Basic 上限 16GB；Plus 每位 1GB、上限 32GB',
 '500MB per referral on Basic (16GB cap); 1GB per referral on Plus (32GB cap)',
 '紹介1人につき500MB（Basicは上限16GB）、Plusは1人1GB・上限32GB', '{}', '{referral}'),
('notion', 'Notion', '軟體訂閱', 'https://www.notion.so/',
 '推薦好友註冊，雙方各得帳戶額度',
 'Both get account credit for a friend signup',
 '友達の登録で双方にアカウントクレジット', '{}', '{referral}'),
('canva', 'Canva', '軟體訂閱', 'https://www.canva.com/',
 '推薦好友，雙方各得 Pro 免費使用期',
 'Both get free Pro time for a friend signup',
 '友達紹介で双方にProの無料期間', '{}', '{referral,discount}'), -- 榜 71
('grammarly', 'Grammarly', '軟體訂閱', 'https://www.grammarly.com/',
 '推薦好友訂閱，雙方各得 Premium 使用週期',
 'Both get Premium time for a friend subscription',
 '友達の加入で双方にPremium期間', '{}', '{referral,discount}'),
('1password', '1Password', '軟體訂閱', 'https://1password.com/',
 '推薦好友訂閱，雙方各得免費使用期',
 'Both get free time for a friend subscription',
 '友達の加入で双方に無料期間', '{}', '{referral}'),
('nordvpn', 'NordVPN', '軟體訂閱', 'https://nordvpn.com/',
 '推薦好友訂閱，雙方各得免費月份，另有長約折扣碼',
 'Both get free months for a friend subscription, plus long-term plan promo codes',
 '友達の加入で双方に無料月、長期プラン割引コードもあり', '{}', '{referral,discount}'),
('expressvpn', 'ExpressVPN', '軟體訂閱', 'https://www.expressvpn.com/',
 '推薦好友訂閱，雙方各得 30 天免費',
 'Both get 30 days free for a friend subscription',
 '友達の加入で双方に30日無料', '{}', '{referral,discount}'),
('surfshark', 'Surfshark', '軟體訂閱', 'https://surfshark.com/',
 '推薦好友訂閱，雙方各得免費月份',
 'Both get free months for a friend subscription',
 '友達の加入で双方に無料月', '{}', '{referral,discount}'),
('proton', 'Proton', '軟體訂閱', 'https://proton.me/',
 '推薦好友升級付費方案，雙方各得訂閱額度',
 'Both get subscription credit when a friend upgrades',
 '友達の有料プラン加入で双方にクレジット', '{}', '{referral,discount}'),
('todoist', 'Todoist', '軟體訂閱', 'https://todoist.com/',
 '推薦好友，雙方各得 Pro 免費使用期',
 'Both get free Pro time for a friend signup',
 '友達紹介で双方にProの無料期間', '{}', '{referral}'),
('clickup', 'ClickUp', '軟體訂閱', 'https://clickup.com/',
 '推薦好友開通團隊，雙方各得方案折抵',
 'Both get plan credit when a friend starts a workspace',
 '友達のワークスペース開設で双方にプランクレジット', '{}', '{referral,discount}'),
('monday-com', 'monday.com', '軟體訂閱', 'https://monday.com/',
 '推薦好友開通帳戶可得帳戶折抵',
 'Account credit for referring a friend who signs up',
 '友達のアカウント開設紹介でクレジット', '{}', '{referral,discount}'),
('zoom', 'Zoom', '軟體訂閱', 'https://zoom.us/',
 '推薦獎勵與方案訂閱折扣碼',
 'Referral rewards and plan subscription promo codes',
 '紹介特典とプラン割引コード', '{}', '{referral,discount}'), -- 榜 79
('adobe', 'Adobe Creative Cloud', '軟體訂閱', 'https://www.adobe.com/',
 '推薦好友訂閱，雙方各得訂閱折扣',
 'Both get subscription discounts for a friend signup',
 '友達の加入で双方にサブスク割引', '{}', '{referral,discount}'),
('backblaze', 'Backblaze', '軟體訂閱', 'https://www.backblaze.com/',
 '推薦好友訂閱備份，雙方各得一個月免費',
 'Both get a free month for a friend backup subscription',
 '友達のバックアップ加入で双方に1ヶ月無料', '{}', '{referral}'),
('pcloud', 'pCloud', '軟體訂閱', 'https://www.pcloud.com/',
 '推薦好友註冊，雙方各得免費空間',
 'Both get free storage for a friend signup',
 '友達の登録で双方に無料ストレージ', '{}', '{referral}'),
('squarespace', 'Squarespace', '軟體訂閱', 'https://www.squarespace.com/',
 '推薦好友首次訂閱，雙方各得折扣',
 'Both get a discount on a friend first subscription',
 '友達の初回加入で双方に割引', '{}', '{referral,discount}'),
('shopify', 'Shopify', '軟體訂閱', 'https://www.shopify.com/',
 '推薦商家開店可得獎金，另有試用與方案折扣碼',
 'Bonus for referring a merchant, plus trial and plan promo codes',
 '出店者紹介でボーナス、トライアル・プラン割引コードもあり', '{}', '{referral,discount}'),
('hostinger', 'Hostinger', '軟體訂閱', 'https://www.hostinger.com/',
 '推薦好友首購可得 20% 佣金，另有主機方案折扣碼',
 '20% commission on a referral first purchase, plus hosting promo codes',
 '紹介の初回購入で20%コミッション、ホスティング割引コードもあり', '{}', '{referral,discount}'),
('namecheap', 'Namecheap', '軟體訂閱', 'https://www.namecheap.com/',
 '推薦好友消費可得帳戶金，另有網域與主機折扣碼',
 'Account credit for referrals, plus domain and hosting promo codes',
 '紹介でアカウントクレジット、ドメイン・ホスティング割引コードもあり', '{}', '{referral,discount}'),

-- ── 遊戲（6）────────────────────────────────────────────────────
-- 遊戲這類多半是「官方兌換碼」而不是一對一邀請，語意上歸 discount。
-- 有創作者代碼／邀請獎勵的才同時開 referral。
('roblox', 'Roblox', '遊戲', 'https://www.roblox.com/',
 'Robux 與虛寶官方兌換碼',
 'Official Robux and item redemption codes',
 'Robuxとアイテムの公式引換コード', '{}', '{discount}'), -- 榜 60
('fortnite', 'Fortnite', '遊戲', 'https://www.fortnite.com/',
 '創作者支援碼與商城折扣碼',
 'Support-A-Creator codes and shop discount codes',
 'クリエイターサポートコードとショップ割引コード', '{}', '{referral,discount}'), -- 榜 54
('xbox-game-pass', 'Xbox Game Pass', '遊戲', 'https://www.xbox.com/',
 '訂閱折扣碼與好友邀請優惠',
 'Subscription promo codes and friend invite offers',
 'サブスク割引コードと友達招待特典', '{}', '{discount}'),
('playstation-plus', 'PlayStation Plus', '遊戲', 'https://www.playstation.com/',
 '訂閱折扣碼與加值優惠',
 'Subscription promo codes and top-up offers',
 'サブスク割引コードとチャージ特典', '{}', '{discount}'),
('genshin-impact', 'Genshin Impact', '遊戲', 'https://genshin.hoyoverse.com/',
 '官方兌換碼與好友邀請獎勵',
 'Official redemption codes and friend invite rewards',
 '公式引換コードと友達招待特典', '{}', '{referral,discount}'),
('discord', 'Discord', '遊戲', 'https://discord.com/',
 'Nitro 訂閱折扣碼與伺服器加成優惠',
 'Nitro subscription promo codes and server boost offers',
 'Nitroサブスク割引コードとサーバーブースト特典', '{}', '{discount}'), -- 榜 47

-- ── 工具生產力（8）──────────────────────────────────────────────
('life360', 'Life360', '工具生產力', 'https://www.life360.com/',
 '推薦好友訂閱，雙方各得會員折抵',
 'Both get membership credit for a friend subscription',
 '友達の加入で双方に会員クレジット', '{}', '{referral,discount}'), -- 榜 25
('ticketmaster', 'Ticketmaster', '工具生產力', 'https://www.ticketmaster.com/',
 '購票折扣碼與預售碼',
 'Ticket promo codes and presale codes',
 'チケット割引コードとプリセールコード', '{US}', '{discount}'), -- 榜 37
('seatgeek', 'SeatGeek', '工具生產力', 'https://seatgeek.com/',
 '推薦好友首次購票，雙方各得 20 美元購票金',
 'Both get $20 in ticket credit on a friend first purchase',
 '友達の初回購入で双方に20ドルのチケットクレジット', '{US}', '{referral,discount}'),
('stubhub', 'StubHub', '工具生產力', 'https://www.stubhub.com/',
 '推薦好友購票，雙方各得購票折抵',
 'Both get ticket credit for a friend purchase',
 '友達の購入で双方にチケットクレジット', '{US}', '{referral,discount}'),
('rover', 'Rover', '工具生產力', 'https://www.rover.com/',
 '推薦好友首次預約寵物服務，雙方各得 20 美元',
 'Both get $20 on a friend first pet service booking',
 '友達の初回予約で双方に20ドル', '{US}', '{referral,discount}'),
('wag', 'Wag!', '工具生產力', 'https://wagwalking.com/',
 '推薦好友使用遛狗服務，雙方各得服務金',
 'Both get service credit for a friend signup',
 '友達の利用開始で双方にサービスクレジット', '{US}', '{referral}'),
('taskrabbit', 'TaskRabbit', '工具生產力', 'https://www.taskrabbit.com/',
 '推薦好友完成首次任務，雙方各得任務折抵',
 'Both get task credit on a friend first booking',
 '友達の初回依頼で双方にタスククレジット', '{US}', '{referral,discount}'),
('thumbtack', 'Thumbtack', '工具生產力', 'https://www.thumbtack.com/',
 '推薦好友媒合服務，雙方各得服務折抵',
 'Both get service credit for a friend booking',
 '友達の利用で双方にサービスクレジット', '{US}', '{referral}'),

-- ── 保險（6）────────────────────────────────────────────────────
('lemonade', 'Lemonade', '保險', 'https://www.lemonade.com/',
 '推薦好友投保，雙方各得保費折抵',
 'Both get premium credit when a friend gets a policy',
 '友達の契約で双方に保険料クレジット', '{US}', '{referral}'),
('root-insurance', 'Root Insurance', '保險', 'https://www.joinroot.com/',
 '推薦好友投保車險，雙方各得現金獎勵',
 'Both get cash when a friend buys a policy',
 '友達の契約で双方に現金特典', '{US}', '{referral}'),
('geico', 'GEICO', '保險', 'https://www.geico.com/',
 '推薦好友投保可得獎勵',
 'Reward for referring a friend who buys a policy',
 '友達の契約紹介で特典', '{US}', '{referral}'),
('progressive', 'Progressive', '保險', 'https://www.progressive.com/',
 '推薦好友取得報價可得獎勵',
 'Reward for referring a friend who gets a quote',
 '友達の見積り紹介で特典', '{US}', '{referral}'),
('healthy-paws', 'Healthy Paws', '保險', 'https://www.healthypawspetinsurance.com/',
 '推薦好友投保寵物險可得 25 美元優惠券',
 'A $25 coupon for referring a friend to pet insurance',
 'ペット保険の友達紹介で25ドルクーポン', '{US}', '{referral}'),
('ethos', 'Ethos Life', '保險', 'https://www.ethoslife.com/',
 '推薦好友投保壽險可得獎勵',
 'Reward for referring a friend who buys life insurance',
 '生命保険の友達紹介で特典', '{US}', '{referral}')

) AS v(slug, name, category_name, signup_url,
       reward_desc, reward_desc_en, reward_desc_ja,
       countries, allowed_code_types)
JOIN referral_code_bonus.merchant_categories c ON c.name = v.category_name
ON CONFLICT (slug) DO NOTHING;

COMMIT;

-- 套用後可以用這句確認每個分類收了幾家：
--   SELECT c.name, count(*) FROM referral_code_bonus.merchants m
--   JOIN referral_code_bonus.merchant_categories c ON c.id = m.category_id
--   GROUP BY c.name ORDER BY count(*) DESC;
