// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: codes.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addCodeImpressions = `-- name: AddCodeImpressions :exec
UPDATE referral_code_bonus.referral_codes
SET impressions = impressions + $1::bigint
WHERE id = ANY($2::uuid[])
`

type AddCodeImpressionsParams struct {
	Delta   int64       `json:"delta"`
	CodeIds []uuid.UUID `json:"code_ids"`
}

func (q *Queries) AddCodeImpressions(ctx context.Context, arg AddCodeImpressionsParams) error {
	_, err := q.db.Exec(ctx, addCodeImpressions, arg.Delta, arg.CodeIds)
	return err
}

const countPendingCodes = `-- name: CountPendingCodes :one
SELECT count(*) FROM referral_code_bonus.referral_codes WHERE status = 'pending'
`

func (q *Queries) CountPendingCodes(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingCodes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCode = `-- name: CreateCode :one
INSERT INTO referral_code_bonus.referral_codes (user_id, merchant_id, code, note, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, merchant_id, code, note, status, expires_at, quality_score, impressions, created_at, activated_at, updated_at
`

type CreateCodeParams struct {
	UserID     uuid.UUID `json:"user_id"`
	MerchantID uuid.UUID `json:"merchant_id"`
	Code       string    `json:"code"`
	Note       string    `json:"note"`
	ExpiresAt  time.Time `json:"expires_at"`
}

func (q *Queries) CreateCode(ctx context.Context, arg CreateCodeParams) (ReferralCode, error) {
	row := q.db.QueryRow(ctx, createCode,
		arg.UserID,
		arg.MerchantID,
		arg.Code,
		arg.Note,
		arg.ExpiresAt,
	)
	var i ReferralCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MerchantID,
		&i.Code,
		&i.Note,
		&i.Status,
		&i.ExpiresAt,
		&i.QualityScore,
		&i.Impressions,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCodeReport = `-- name: CreateCodeReport :one
INSERT INTO referral_code_bonus.code_reports (code_id, reporter_id, device_hash, result)
VALUES ($1, $2, $3, $4)
ON CONFLICT (code_id, device_hash) DO NOTHING
RETURNING id, code_id, reporter_id, device_hash, result, created_at
`

type CreateCodeReportParams struct {
	CodeID     uuid.UUID  `json:"code_id"`
	ReporterID *uuid.UUID `json:"reporter_id"`
	DeviceHash string     `json:"device_hash"`
	Result     string     `json:"result"`
}

func (q *Queries) CreateCodeReport(ctx context.Context, arg CreateCodeReportParams) (CodeReport, error) {
	row := q.db.QueryRow(ctx, createCodeReport,
		arg.CodeID,
		arg.ReporterID,
		arg.DeviceHash,
		arg.Result,
	)
	var i CodeReport
	err := row.Scan(
		&i.ID,
		&i.CodeID,
		&i.ReporterID,
		&i.DeviceHash,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const createCodeReview = `-- name: CreateCodeReview :one
INSERT INTO referral_code_bonus.code_reviews (code_id, admin_id, action, reason)
VALUES ($1, $2, $3, $4)
RETURNING id, code_id, admin_id, action, reason, created_at
`

type CreateCodeReviewParams struct {
	CodeID  uuid.UUID  `json:"code_id"`
	AdminID *uuid.UUID `json:"admin_id"`
	Action  string     `json:"action"`
	Reason  string     `json:"reason"`
}

func (q *Queries) CreateCodeReview(ctx context.Context, arg CreateCodeReviewParams) (CodeReview, error) {
	row := q.db.QueryRow(ctx, createCodeReview,
		arg.CodeID,
		arg.AdminID,
		arg.Action,
		arg.Reason,
	)
	var i CodeReview
	err := row.Scan(
		&i.ID,
		&i.CodeID,
		&i.AdminID,
		&i.Action,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const expireOverdueCodes = `-- name: ExpireOverdueCodes :many
UPDATE referral_code_bonus.referral_codes
SET status = 'expired', updated_at = now()
WHERE status = 'active' AND expires_at <= now()
RETURNING id, user_id, merchant_id
`

type ExpireOverdueCodesRow struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	MerchantID uuid.UUID `json:"merchant_id"`
}

// 到期下架排程用。回傳受影響的碼以便通知上架者。
func (q *Queries) ExpireOverdueCodes(ctx context.Context) ([]ExpireOverdueCodesRow, error) {
	rows, err := q.db.Query(ctx, expireOverdueCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpireOverdueCodesRow{}
	for rows.Next() {
		var i ExpireOverdueCodesRow
		if err := rows.Scan(&i.ID, &i.UserID, &i.MerchantID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCodeByID = `-- name: GetCodeByID :one
SELECT id, user_id, merchant_id, code, note, status, expires_at, quality_score, impressions, created_at, activated_at, updated_at FROM referral_code_bonus.referral_codes WHERE id = $1
`

func (q *Queries) GetCodeByID(ctx context.Context, id uuid.UUID) (ReferralCode, error) {
	row := q.db.QueryRow(ctx, getCodeByID, id)
	var i ReferralCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MerchantID,
		&i.Code,
		&i.Note,
		&i.Status,
		&i.ExpiresAt,
		&i.QualityScore,
		&i.Impressions,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecentReportStats = `-- name: GetRecentReportStats :one
SELECT
    count(*)                                        AS total,
    count(*) FILTER (WHERE result = 'worked')       AS worked,
    count(*) FILTER (WHERE result <> 'worked')      AS failed
FROM (
    SELECT result FROM referral_code_bonus.code_reports
    WHERE code_id = $1
    ORDER BY created_at DESC
    LIMIT 10
) recent
`

type GetRecentReportStatsRow struct {
	Total  int64 `json:"total"`
	Worked int64 `json:"worked"`
	Failed int64 `json:"failed"`
}

// 自動下架的判定素材：只看最近 10 筆，讓碼有機會從舊的負評裡翻身
// （服務商重啟活動時，舊的 failed 不該永遠壓著）。
func (q *Queries) GetRecentReportStats(ctx context.Context, codeID uuid.UUID) (GetRecentReportStatsRow, error) {
	row := q.db.QueryRow(ctx, getRecentReportStats, codeID)
	var i GetRecentReportStatsRow
	err := row.Scan(&i.Total, &i.Worked, &i.Failed)
	return i, err
}

const listActiveCodesForMerchant = `-- name: ListActiveCodesForMerchant :many
SELECT
    c.id, c.user_id, c.code, c.note, c.quality_score, c.impressions,
    c.expires_at, c.created_at, c.activated_at,
    u.display_name AS owner_name,
    u.avatar_url   AS owner_avatar_url,
    (SELECT count(*) FROM referral_code_bonus.code_reports r
      WHERE r.code_id = c.id AND r.result = 'worked') AS worked_count,
    (SELECT count(*) FROM referral_code_bonus.code_reports r
      WHERE r.code_id = c.id AND r.result <> 'worked') AS failed_count,
    EXISTS (
        SELECT 1 FROM referral_code_bonus.subscriptions s
        WHERE s.user_id = c.user_id
          AND s.is_active
          AND (s.expires_at IS NULL OR s.expires_at > now())
    ) AS owner_is_pro
FROM referral_code_bonus.referral_codes c
JOIN referral_code_bonus.users u ON u.id = c.user_id
WHERE c.merchant_id = $1
  AND c.status = 'active'
  AND c.expires_at > now()
ORDER BY c.quality_score DESC, c.created_at DESC
LIMIT 200
`

type ListActiveCodesForMerchantRow struct {
	ID             uuid.UUID  `json:"id"`
	UserID         uuid.UUID  `json:"user_id"`
	Code           string     `json:"code"`
	Note           string     `json:"note"`
	QualityScore   int32      `json:"quality_score"`
	Impressions    int64      `json:"impressions"`
	ExpiresAt      time.Time  `json:"expires_at"`
	CreatedAt      time.Time  `json:"created_at"`
	ActivatedAt    *time.Time `json:"activated_at"`
	OwnerName      string     `json:"owner_name"`
	OwnerAvatarUrl *string    `json:"owner_avatar_url"`
	WorkedCount    int64      `json:"worked_count"`
	FailedCount    int64      `json:"failed_count"`
	OwnerIsPro     bool       `json:"owner_is_pro"`
}

// 服務商頁的候選池。權重計算放在 Go 端（internal/ranking），SQL 只負責撈素材：
// 一次上限 200 筆，超過這個數量的長尾對抽樣結果影響已經很小。
// 上架者是 Pro 才給排序加成（is_pro），跟免費上架張數上限是同一個賣點延伸。
func (q *Queries) ListActiveCodesForMerchant(ctx context.Context, merchantID uuid.UUID) ([]ListActiveCodesForMerchantRow, error) {
	rows, err := q.db.Query(ctx, listActiveCodesForMerchant, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveCodesForMerchantRow{}
	for rows.Next() {
		var i ListActiveCodesForMerchantRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Code,
			&i.Note,
			&i.QualityScore,
			&i.Impressions,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.ActivatedAt,
			&i.OwnerName,
			&i.OwnerAvatarUrl,
			&i.WorkedCount,
			&i.FailedCount,
			&i.OwnerIsPro,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCodeReviews = `-- name: ListCodeReviews :many
SELECT id, code_id, admin_id, action, reason, created_at FROM referral_code_bonus.code_reviews WHERE code_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListCodeReviews(ctx context.Context, codeID uuid.UUID) ([]CodeReview, error) {
	rows, err := q.db.Query(ctx, listCodeReviews, codeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CodeReview{}
	for rows.Next() {
		var i CodeReview
		if err := rows.Scan(
			&i.ID,
			&i.CodeID,
			&i.AdminID,
			&i.Action,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyCodes = `-- name: ListMyCodes :many
SELECT c.id, c.user_id, c.merchant_id, c.code, c.note, c.status, c.expires_at, c.quality_score, c.impressions, c.created_at, c.activated_at, c.updated_at, m.slug AS merchant_slug, m.name AS merchant_name, m.logo_url AS merchant_logo_url
FROM referral_code_bonus.referral_codes c
JOIN referral_code_bonus.merchants m ON m.id = c.merchant_id
WHERE c.user_id = $1
ORDER BY c.created_at DESC
`

type ListMyCodesRow struct {
	ID              uuid.UUID  `json:"id"`
	UserID          uuid.UUID  `json:"user_id"`
	MerchantID      uuid.UUID  `json:"merchant_id"`
	Code            string     `json:"code"`
	Note            string     `json:"note"`
	Status          string     `json:"status"`
	ExpiresAt       time.Time  `json:"expires_at"`
	QualityScore    int32      `json:"quality_score"`
	Impressions     int64      `json:"impressions"`
	CreatedAt       time.Time  `json:"created_at"`
	ActivatedAt     *time.Time `json:"activated_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
	MerchantSlug    string     `json:"merchant_slug"`
	MerchantName    string     `json:"merchant_name"`
	MerchantLogoUrl *string    `json:"merchant_logo_url"`
}

func (q *Queries) ListMyCodes(ctx context.Context, userID uuid.UUID) ([]ListMyCodesRow, error) {
	rows, err := q.db.Query(ctx, listMyCodes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyCodesRow{}
	for rows.Next() {
		var i ListMyCodesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MerchantID,
			&i.Code,
			&i.Note,
			&i.Status,
			&i.ExpiresAt,
			&i.QualityScore,
			&i.Impressions,
			&i.CreatedAt,
			&i.ActivatedAt,
			&i.UpdatedAt,
			&i.MerchantSlug,
			&i.MerchantName,
			&i.MerchantLogoUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingCodes = `-- name: ListPendingCodes :many
SELECT c.id, c.user_id, c.merchant_id, c.code, c.note, c.status, c.expires_at, c.quality_score, c.impressions, c.created_at, c.activated_at, c.updated_at, m.slug AS merchant_slug, m.name AS merchant_name,
       m.code_format_regex, u.email AS owner_email, u.display_name AS owner_name,
       EXISTS (
           SELECT 1 FROM referral_code_bonus.subscriptions s
           WHERE s.user_id = c.user_id
             AND s.is_active
             AND (s.expires_at IS NULL OR s.expires_at > now())
       ) AS owner_is_pro
FROM referral_code_bonus.referral_codes c
JOIN referral_code_bonus.merchants m ON m.id = c.merchant_id
JOIN referral_code_bonus.users u     ON u.id = c.user_id
WHERE c.status = 'pending'
ORDER BY owner_is_pro DESC, c.created_at
LIMIT $1 OFFSET $2
`

type ListPendingCodesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListPendingCodesRow struct {
	ID              uuid.UUID  `json:"id"`
	UserID          uuid.UUID  `json:"user_id"`
	MerchantID      uuid.UUID  `json:"merchant_id"`
	Code            string     `json:"code"`
	Note            string     `json:"note"`
	Status          string     `json:"status"`
	ExpiresAt       time.Time  `json:"expires_at"`
	QualityScore    int32      `json:"quality_score"`
	Impressions     int64      `json:"impressions"`
	CreatedAt       time.Time  `json:"created_at"`
	ActivatedAt     *time.Time `json:"activated_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
	MerchantSlug    string     `json:"merchant_slug"`
	MerchantName    string     `json:"merchant_name"`
	CodeFormatRegex *string    `json:"code_format_regex"`
	OwnerEmail      string     `json:"owner_email"`
	OwnerName       string     `json:"owner_name"`
	OwnerIsPro      bool       `json:"owner_is_pro"`
}

// 待審佇列。Pro 的碼排在前面，兌現 paywall 的「優先審核」賣點——
// 排序的新鮮度加成是從 activated_at 起算的，審核多等一天就等於黃金期晚一天開始，
// 所以這裡不優先的話，Pro 買到的黃金期會被佇列的等待時間吃掉一部分。
// 同一層級內仍照送審時間先後，免費的碼不會被無限期插隊。
func (q *Queries) ListPendingCodes(ctx context.Context, arg ListPendingCodesParams) ([]ListPendingCodesRow, error) {
	rows, err := q.db.Query(ctx, listPendingCodes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingCodesRow{}
	for rows.Next() {
		var i ListPendingCodesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MerchantID,
			&i.Code,
			&i.Note,
			&i.Status,
			&i.ExpiresAt,
			&i.QualityScore,
			&i.Impressions,
			&i.CreatedAt,
			&i.ActivatedAt,
			&i.UpdatedAt,
			&i.MerchantSlug,
			&i.MerchantName,
			&i.CodeFormatRegex,
			&i.OwnerEmail,
			&i.OwnerName,
			&i.OwnerIsPro,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCodeStatus = `-- name: SetCodeStatus :one
UPDATE referral_code_bonus.referral_codes
SET status = $2,
    activated_at = CASE WHEN $2 = 'active' AND activated_at IS NULL THEN now() ELSE activated_at END,
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, merchant_id, code, note, status, expires_at, quality_score, impressions, created_at, activated_at, updated_at
`

type SetCodeStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) SetCodeStatus(ctx context.Context, arg SetCodeStatusParams) (ReferralCode, error) {
	row := q.db.QueryRow(ctx, setCodeStatus, arg.ID, arg.Status)
	var i ReferralCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MerchantID,
		&i.Code,
		&i.Note,
		&i.Status,
		&i.ExpiresAt,
		&i.QualityScore,
		&i.Impressions,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCodeQualityScore = `-- name: UpdateCodeQualityScore :exec
UPDATE referral_code_bonus.referral_codes
SET quality_score = $2, updated_at = now()
WHERE id = $1
`

type UpdateCodeQualityScoreParams struct {
	ID           uuid.UUID `json:"id"`
	QualityScore int32     `json:"quality_score"`
}

func (q *Queries) UpdateCodeQualityScore(ctx context.Context, arg UpdateCodeQualityScoreParams) error {
	_, err := q.db.Exec(ctx, updateCodeQualityScore, arg.ID, arg.QualityScore)
	return err
}
