// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createEventPartition = `-- name: CreateEventPartition :exec
SELECT referral_code_bonus.ensure_event_partition($1::date)
`

func (q *Queries) CreateEventPartition(ctx context.Context, month time.Time) error {
	_, err := q.db.Exec(ctx, createEventPartition, month)
	return err
}

const getCodeStats = `-- name: GetCodeStats :one
SELECT
    count(*) FILTER (WHERE event_type = 'impression') AS impressions,
    count(*) FILTER (WHERE event_type = 'click')      AS clicks,
    count(*) FILTER (WHERE event_type = 'copy')       AS copies
FROM referral_code_bonus.code_events
WHERE code_id = $1 AND created_at > now() - $2::int * interval '1 day'
`

type GetCodeStatsParams struct {
	CodeID     uuid.UUID `json:"code_id"`
	WindowDays int32     `json:"window_days"`
}

type GetCodeStatsRow struct {
	Impressions int64 `json:"impressions"`
	Clicks      int64 `json:"clicks"`
	Copies      int64 `json:"copies"`
}

// 上架者儀表板。
func (q *Queries) GetCodeStats(ctx context.Context, arg GetCodeStatsParams) (GetCodeStatsRow, error) {
	row := q.db.QueryRow(ctx, getCodeStats, arg.CodeID, arg.WindowDays)
	var i GetCodeStatsRow
	err := row.Scan(&i.Impressions, &i.Clicks, &i.Copies)
	return i, err
}

const hasRecentImpression = `-- name: HasRecentImpression :one
SELECT EXISTS (
    SELECT 1 FROM referral_code_bonus.code_events
    WHERE code_id = $1
      AND device_hash = $2
      AND event_type = 'impression'
      AND created_at > now() - interval '30 minutes'
)
`

type HasRecentImpressionParams struct {
	CodeID     uuid.UUID `json:"code_id"`
	DeviceHash string    `json:"device_hash"`
}

// 點擊計費要求「先有曝光才算數」，Phase 3 會用這個擋直接打 API 刷點擊。
func (q *Queries) HasRecentImpression(ctx context.Context, arg HasRecentImpressionParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasRecentImpression, arg.CodeID, arg.DeviceHash)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO referral_code_bonus.code_events (code_id, merchant_id, event_type, user_id, device_hash, ip_hash, is_billable)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertEventParams struct {
	CodeID     uuid.UUID  `json:"code_id"`
	MerchantID uuid.UUID  `json:"merchant_id"`
	EventType  string     `json:"event_type"`
	UserID     *uuid.UUID `json:"user_id"`
	DeviceHash string     `json:"device_hash"`
	IpHash     string     `json:"ip_hash"`
	IsBillable bool       `json:"is_billable"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.Exec(ctx, insertEvent,
		arg.CodeID,
		arg.MerchantID,
		arg.EventType,
		arg.UserID,
		arg.DeviceHash,
		arg.IpHash,
		arg.IsBillable,
	)
	return err
}
