// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: merchant_suggestions.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countActiveMerchantsByName = `-- name: CountActiveMerchantsByName :one
SELECT count(*) FROM referral_code_bonus.merchants
WHERE is_active AND lower(name) = lower($1::text)
`

// 提報之前先確認目錄裡沒有這家（同名、不分大小寫）。
// 只看上架中的：停用的那些是還沒補完資料的草稿，使用者在 app 裡看不到，
// 他提報是合理的，那筆建議也剛好提醒後台「有人在等這家」。
func (q *Queries) CountActiveMerchantsByName(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveMerchantsByName, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingSuggestionsByUser = `-- name: CountPendingSuggestionsByUser :one
SELECT count(*) FROM referral_code_bonus.merchant_suggestions
WHERE user_id = $1 AND status = 'pending'
`

// 一個人同時掛著幾筆待審。上限由 handler 決定 —— 這裡只負責數。
func (q *Queries) CountPendingSuggestionsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingSuggestionsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMerchantSuggestion = `-- name: CreateMerchantSuggestion :one

INSERT INTO referral_code_bonus.merchant_suggestions (user_id, name, signup_url, note)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, signup_url, note, status, reviewed_by, reviewed_at, review_reason, merchant_id, created_at
`

type CreateMerchantSuggestionParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Name      string    `json:"name"`
	SignupUrl string    `json:"signup_url"`
	Note      string    `json:"note"`
}

// 使用者提報希望上架的平台，後台審核後建成停用的服務商草稿。
// 資料模型與各欄位的取捨見 db/migrations/00016_merchant_suggestions.sql。
func (q *Queries) CreateMerchantSuggestion(ctx context.Context, arg CreateMerchantSuggestionParams) (MerchantSuggestion, error) {
	row := q.db.QueryRow(ctx, createMerchantSuggestion,
		arg.UserID,
		arg.Name,
		arg.SignupUrl,
		arg.Note,
	)
	var i MerchantSuggestion
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.SignupUrl,
		&i.Note,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewReason,
		&i.MerchantID,
		&i.CreatedAt,
	)
	return i, err
}

const getMerchantSuggestionByID = `-- name: GetMerchantSuggestionByID :one
SELECT id, user_id, name, signup_url, note, status, reviewed_by, reviewed_at, review_reason, merchant_id, created_at FROM referral_code_bonus.merchant_suggestions WHERE id = $1
`

func (q *Queries) GetMerchantSuggestionByID(ctx context.Context, id uuid.UUID) (MerchantSuggestion, error) {
	row := q.db.QueryRow(ctx, getMerchantSuggestionByID, id)
	var i MerchantSuggestion
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.SignupUrl,
		&i.Note,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewReason,
		&i.MerchantID,
		&i.CreatedAt,
	)
	return i, err
}

const listPendingMerchantSuggestions = `-- name: ListPendingMerchantSuggestions :many
SELECT
    s.id, s.user_id, s.name, s.signup_url, s.note, s.status, s.reviewed_by, s.reviewed_at, s.review_reason, s.merchant_id, s.created_at,
    u.email AS owner_email,
    u.display_name AS owner_name,
    count(*) OVER () AS total_count
FROM referral_code_bonus.merchant_suggestions s
JOIN referral_code_bonus.users u ON u.id = s.user_id
WHERE s.status = 'pending'
ORDER BY s.created_at
LIMIT $1 OFFSET $2
`

type ListPendingMerchantSuggestionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListPendingMerchantSuggestionsRow struct {
	ID           uuid.UUID  `json:"id"`
	UserID       uuid.UUID  `json:"user_id"`
	Name         string     `json:"name"`
	SignupUrl    string     `json:"signup_url"`
	Note         string     `json:"note"`
	Status       string     `json:"status"`
	ReviewedBy   *uuid.UUID `json:"reviewed_by"`
	ReviewedAt   *time.Time `json:"reviewed_at"`
	ReviewReason string     `json:"review_reason"`
	MerchantID   *uuid.UUID `json:"merchant_id"`
	CreatedAt    time.Time  `json:"created_at"`
	OwnerEmail   string     `json:"owner_email"`
	OwnerName    string     `json:"owner_name"`
	TotalCount   int64      `json:"total_count"`
}

// 後台待審清單。最舊的排前面，先進先審。
func (q *Queries) ListPendingMerchantSuggestions(ctx context.Context, arg ListPendingMerchantSuggestionsParams) ([]ListPendingMerchantSuggestionsRow, error) {
	rows, err := q.db.Query(ctx, listPendingMerchantSuggestions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingMerchantSuggestionsRow{}
	for rows.Next() {
		var i ListPendingMerchantSuggestionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.SignupUrl,
			&i.Note,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.ReviewReason,
			&i.MerchantID,
			&i.CreatedAt,
			&i.OwnerEmail,
			&i.OwnerName,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reviewMerchantSuggestion = `-- name: ReviewMerchantSuggestion :one
UPDATE referral_code_bonus.merchant_suggestions
SET status = $1::text,
    reviewed_by = $2,
    reviewed_at = now(),
    review_reason = $3,
    merchant_id = $4
WHERE id = $5 AND status = 'pending'
RETURNING id, user_id, name, signup_url, note, status, reviewed_by, reviewed_at, review_reason, merchant_id, created_at
`

type ReviewMerchantSuggestionParams struct {
	Status       string     `json:"status"`
	ReviewedBy   *uuid.UUID `json:"reviewed_by"`
	ReviewReason string     `json:"review_reason"`
	MerchantID   *uuid.UUID `json:"merchant_id"`
	ID           uuid.UUID  `json:"id"`
}

// 審核只會發生一次，所以條件帶上 status = 'pending'：兩個 admin 同時按下通過時，
// 第二個會撈不到列（回 ErrNoRows），由 handler 轉成「這筆已經審過了」，
// 而不是把服務商建成兩家。
func (q *Queries) ReviewMerchantSuggestion(ctx context.Context, arg ReviewMerchantSuggestionParams) (MerchantSuggestion, error) {
	row := q.db.QueryRow(ctx, reviewMerchantSuggestion,
		arg.Status,
		arg.ReviewedBy,
		arg.ReviewReason,
		arg.MerchantID,
		arg.ID,
	)
	var i MerchantSuggestion
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.SignupUrl,
		&i.Note,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewReason,
		&i.MerchantID,
		&i.CreatedAt,
	)
	return i, err
}
