// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: merchants.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addMerchantCountry = `-- name: AddMerchantCountry :execrows
UPDATE referral_code_bonus.merchants
SET countries = (
        SELECT array_agg(c ORDER BY c) FROM (SELECT DISTINCT unnest(countries || $1::text) AS c) u
    ),
    updated_at = now()
WHERE slug = $2 AND NOT (countries @> ARRAY[$1::text])
`

type AddMerchantCountryParams struct {
	Country string `json:"country"`
	Slug    string `json:"slug"`
}

// 同一家 app 會同時出現在好幾個國家的排行榜。那是同一家服務商，不該建成好幾列
// （slug 是唯一的、推薦碼掛在 merchant_id 上，拆列會把同一家的碼池切開），
// 所以只把國別加進 countries 陣列。
//
// 已經有這個國家就不動它（連 updated_at 都不碰），回傳的列數就是「有沒有真的加到」。
func (q *Queries) AddMerchantCountry(ctx context.Context, arg AddMerchantCountryParams) (int64, error) {
	result, err := q.db.Exec(ctx, addMerchantCountry, arg.Country, arg.Slug)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO referral_code_bonus.merchant_categories (name, sort_order, image_url, name_en, name_ja)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, sort_order, created_at, image_url, name_en, name_ja
`

type CreateCategoryParams struct {
	Name      string  `json:"name"`
	SortOrder int32   `json:"sort_order"`
	ImageUrl  *string `json:"image_url"`
	NameEn    *string `json:"name_en"`
	NameJa    *string `json:"name_ja"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (MerchantCategory, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.Name,
		arg.SortOrder,
		arg.ImageUrl,
		arg.NameEn,
		arg.NameJa,
	)
	var i MerchantCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
		&i.ImageUrl,
		&i.NameEn,
		&i.NameJa,
	)
	return i, err
}

const createImportedMerchant = `-- name: CreateImportedMerchant :one
INSERT INTO referral_code_bonus.merchants (slug, name, category_id, logo_url, signup_url, countries, is_active)
VALUES ($1, $2, $3, $4, $5, $6, false)
RETURNING id, slug, name, category_id, logo_url, signup_url, reward_desc, code_format_regex, is_active, created_at, updated_at, countries, reward_desc_en, reward_desc_ja, allowed_code_types, discount_code_format_regex
`

type CreateImportedMerchantParams struct {
	Slug       string    `json:"slug"`
	Name       string    `json:"name"`
	CategoryID uuid.UUID `json:"category_id"`
	LogoUrl    *string   `json:"logo_url"`
	SignupUrl  string    `json:"signup_url"`
	Countries  []string  `json:"countries"`
}

// 匯入用（cmd/appimport）。從 App Store 拉回來的只有名稱、圖示與官網，
// 獎勵說明爬不到，所以一律建成停用的草稿，等後台補完 reward_desc 再上架 ——
// 沒有獎勵說明的服務商放上目錄，使用者點進去只會看到空白。
func (q *Queries) CreateImportedMerchant(ctx context.Context, arg CreateImportedMerchantParams) (Merchant, error) {
	row := q.db.QueryRow(ctx, createImportedMerchant,
		arg.Slug,
		arg.Name,
		arg.CategoryID,
		arg.LogoUrl,
		arg.SignupUrl,
		arg.Countries,
	)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CategoryID,
		&i.LogoUrl,
		&i.SignupUrl,
		&i.RewardDesc,
		&i.CodeFormatRegex,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Countries,
		&i.RewardDescEn,
		&i.RewardDescJa,
		&i.AllowedCodeTypes,
		&i.DiscountCodeFormatRegex,
	)
	return i, err
}

const createMerchant = `-- name: CreateMerchant :one
INSERT INTO referral_code_bonus.merchants (slug, name, category_id, logo_url, signup_url, reward_desc, code_format_regex, countries, reward_desc_en, reward_desc_ja, allowed_code_types, discount_code_format_regex)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, slug, name, category_id, logo_url, signup_url, reward_desc, code_format_regex, is_active, created_at, updated_at, countries, reward_desc_en, reward_desc_ja, allowed_code_types, discount_code_format_regex
`

type CreateMerchantParams struct {
	Slug                    string    `json:"slug"`
	Name                    string    `json:"name"`
	CategoryID              uuid.UUID `json:"category_id"`
	LogoUrl                 *string   `json:"logo_url"`
	SignupUrl               string    `json:"signup_url"`
	RewardDesc              string    `json:"reward_desc"`
	CodeFormatRegex         *string   `json:"code_format_regex"`
	Countries               []string  `json:"countries"`
	RewardDescEn            *string   `json:"reward_desc_en"`
	RewardDescJa            *string   `json:"reward_desc_ja"`
	AllowedCodeTypes        []string  `json:"allowed_code_types"`
	DiscountCodeFormatRegex *string   `json:"discount_code_format_regex"`
}

func (q *Queries) CreateMerchant(ctx context.Context, arg CreateMerchantParams) (Merchant, error) {
	row := q.db.QueryRow(ctx, createMerchant,
		arg.Slug,
		arg.Name,
		arg.CategoryID,
		arg.LogoUrl,
		arg.SignupUrl,
		arg.RewardDesc,
		arg.CodeFormatRegex,
		arg.Countries,
		arg.RewardDescEn,
		arg.RewardDescJa,
		arg.AllowedCodeTypes,
		arg.DiscountCodeFormatRegex,
	)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CategoryID,
		&i.LogoUrl,
		&i.SignupUrl,
		&i.RewardDesc,
		&i.CodeFormatRegex,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Countries,
		&i.RewardDescEn,
		&i.RewardDescJa,
		&i.AllowedCodeTypes,
		&i.DiscountCodeFormatRegex,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM referral_code_bonus.merchant_categories WHERE id = $1
`

// merchants.category_id 是 FK 且沒有 ON DELETE，還有服務商掛著的分類刪不掉，
// 交給呼叫端把 23503 轉成看得懂的錯誤（見 store.IsForeignKeyViolation）。
func (q *Queries) DeleteCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCategory, id)
	return err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, name, sort_order, created_at, image_url, name_en, name_ja FROM referral_code_bonus.merchant_categories WHERE id = $1
`

func (q *Queries) GetCategoryByID(ctx context.Context, id uuid.UUID) (MerchantCategory, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i MerchantCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
		&i.ImageUrl,
		&i.NameEn,
		&i.NameJa,
	)
	return i, err
}

const getMerchantByID = `-- name: GetMerchantByID :one
SELECT id, slug, name, category_id, logo_url, signup_url, reward_desc, code_format_regex, is_active, created_at, updated_at, countries, reward_desc_en, reward_desc_ja, allowed_code_types, discount_code_format_regex FROM referral_code_bonus.merchants WHERE id = $1
`

func (q *Queries) GetMerchantByID(ctx context.Context, id uuid.UUID) (Merchant, error) {
	row := q.db.QueryRow(ctx, getMerchantByID, id)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CategoryID,
		&i.LogoUrl,
		&i.SignupUrl,
		&i.RewardDesc,
		&i.CodeFormatRegex,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Countries,
		&i.RewardDescEn,
		&i.RewardDescJa,
		&i.AllowedCodeTypes,
		&i.DiscountCodeFormatRegex,
	)
	return i, err
}

const getMerchantBySlug = `-- name: GetMerchantBySlug :one
SELECT m.id, m.slug, m.name, m.category_id, m.logo_url, m.signup_url, m.reward_desc, m.code_format_regex, m.is_active, m.created_at, m.updated_at, m.countries, m.reward_desc_en, m.reward_desc_ja, m.allowed_code_types, m.discount_code_format_regex, c.name AS category_name, c.name_en AS category_name_en, c.name_ja AS category_name_ja
FROM referral_code_bonus.merchants m
JOIN referral_code_bonus.merchant_categories c ON c.id = m.category_id
WHERE m.slug = $1 AND m.is_active
`

type GetMerchantBySlugRow struct {
	ID                      uuid.UUID `json:"id"`
	Slug                    string    `json:"slug"`
	Name                    string    `json:"name"`
	CategoryID              uuid.UUID `json:"category_id"`
	LogoUrl                 *string   `json:"logo_url"`
	SignupUrl               string    `json:"signup_url"`
	RewardDesc              string    `json:"reward_desc"`
	CodeFormatRegex         *string   `json:"code_format_regex"`
	IsActive                bool      `json:"is_active"`
	CreatedAt               time.Time `json:"created_at"`
	UpdatedAt               time.Time `json:"updated_at"`
	Countries               []string  `json:"countries"`
	RewardDescEn            *string   `json:"reward_desc_en"`
	RewardDescJa            *string   `json:"reward_desc_ja"`
	AllowedCodeTypes        []string  `json:"allowed_code_types"`
	DiscountCodeFormatRegex *string   `json:"discount_code_format_regex"`
	CategoryName            string    `json:"category_name"`
	CategoryNameEn          *string   `json:"category_name_en"`
	CategoryNameJa          *string   `json:"category_name_ja"`
}

func (q *Queries) GetMerchantBySlug(ctx context.Context, slug string) (GetMerchantBySlugRow, error) {
	row := q.db.QueryRow(ctx, getMerchantBySlug, slug)
	var i GetMerchantBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CategoryID,
		&i.LogoUrl,
		&i.SignupUrl,
		&i.RewardDesc,
		&i.CodeFormatRegex,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Countries,
		&i.RewardDescEn,
		&i.RewardDescJa,
		&i.AllowedCodeTypes,
		&i.DiscountCodeFormatRegex,
		&i.CategoryName,
		&i.CategoryNameEn,
		&i.CategoryNameJa,
	)
	return i, err
}

const listActiveMerchantCountries = `-- name: ListActiveMerchantCountries :many
SELECT c::text AS country, count(*) AS merchant_count
FROM referral_code_bonus.merchants m, unnest(m.countries) AS c
WHERE m.is_active
GROUP BY c
ORDER BY merchant_count DESC, c
`

type ListActiveMerchantCountriesRow struct {
	Country       string `json:"country"`
	MerchantCount int64  `json:"merchant_count"`
}

// app 的地區選單要照「實際有服務商的國家」給，不是寫死一份清單 ——
// 目錄是從 App Store 排行榜匯進來的，涵蓋哪些國家會隨著匯入與停用一直變。
// 寫死的清單遲早會同時出現「選了卻是空的」與「有服務商卻選不到」兩種錯。
//
// countries 是空陣列的服務商（不分地區）不會貢獻任何國家，這是對的：
// 它們在任何地區都看得到，不構成「選這個國家」的理由。
// ::text 不能省：sqlc 推不出 unnest() 的型別，沒有 cast 會產出 interface{}。
func (q *Queries) ListActiveMerchantCountries(ctx context.Context) ([]ListActiveMerchantCountriesRow, error) {
	rows, err := q.db.Query(ctx, listActiveMerchantCountries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveMerchantCountriesRow{}
	for rows.Next() {
		var i ListActiveMerchantCountriesRow
		if err := rows.Scan(&i.Country, &i.MerchantCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, sort_order, created_at, image_url, name_en, name_ja FROM referral_code_bonus.merchant_categories ORDER BY sort_order, name
`

func (q *Queries) ListCategories(ctx context.Context) ([]MerchantCategory, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MerchantCategory{}
	for rows.Next() {
		var i MerchantCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SortOrder,
			&i.CreatedAt,
			&i.ImageUrl,
			&i.NameEn,
			&i.NameJa,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMerchantSlugs = `-- name: ListMerchantSlugs :many
SELECT slug, updated_at FROM referral_code_bonus.merchants WHERE is_active ORDER BY slug
`

type ListMerchantSlugsRow struct {
	Slug      string    `json:"slug"`
	UpdatedAt time.Time `json:"updated_at"`
}

// sitemap 用：所有可索引的服務商 slug。
func (q *Queries) ListMerchantSlugs(ctx context.Context) ([]ListMerchantSlugsRow, error) {
	rows, err := q.db.Query(ctx, listMerchantSlugs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMerchantSlugsRow{}
	for rows.Next() {
		var i ListMerchantSlugsRow
		if err := rows.Scan(&i.Slug, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMerchants = `-- name: ListMerchants :many
SELECT
    m.id, m.slug, m.name, m.category_id, m.logo_url, m.signup_url, m.reward_desc, m.code_format_regex, m.is_active, m.created_at, m.updated_at, m.countries, m.reward_desc_en, m.reward_desc_ja, m.allowed_code_types, m.discount_code_format_regex,
    c.name AS category_name,
    c.name_en AS category_name_en,
    c.name_ja AS category_name_ja,
    coalesce(stat.active_code_count, 0) AS active_code_count,
    stat.soonest_expires_at,
    count(*) OVER () AS total_count
FROM referral_code_bonus.merchants m
JOIN referral_code_bonus.merchant_categories c ON c.id = m.category_id
LEFT JOIN LATERAL (
    SELECT count(*) AS active_code_count, min(rc.expires_at) AS soonest_expires_at
    FROM referral_code_bonus.referral_codes rc
    -- expires_at IS NULL 是永久有效的碼，要算進 active_code_count。
    -- min() 會忽略 NULL，所以 soonest_expires_at 仍是「最快到期的那個碼」，
    -- 全部都是永久碼時回 NULL，前端就不顯示倒數。
    WHERE rc.merchant_id = m.id AND rc.status = 'active'
      AND (rc.expires_at IS NULL OR rc.expires_at > now())
) stat ON true
WHERE m.is_active
  AND ($3::uuid IS NULL OR m.category_id = $3::uuid)
  AND (
    $4::text IS NULL
    OR (
        m.name || ' ' || m.reward_desc || ' ' ||
        coalesce(m.reward_desc_en, '') || ' ' || coalesce(m.reward_desc_ja, '')
    ) ILIKE '%' || $4::text || '%'
    OR (
        c.name || ' ' || coalesce(c.name_en, '') || ' ' || coalesce(c.name_ja, '')
    ) ILIKE '%' || $4::text || '%'
    OR (
        length($5::text) >= 4
        AND extensions.word_similarity($5::text, m.name) >= 0.5
    )
  )
  AND (
    $6::text IS NULL
    OR cardinality(m.countries) = 0
    OR m.countries @> ARRAY[$6::text]
  )
ORDER BY
    -- 命中強度排在地區之前：搜「台新」的人要的是台新，不是「在你的國家、
    -- 而且名字裡剛好有新字」的那一家。沒搜尋時整個 CASE 都是 0，
    -- 排序完全退回原本的，首頁與分類頁的結果一個字都不會變。
    CASE
        WHEN $4::text IS NULL THEN 0
        WHEN m.name ILIKE $4::text THEN 0                 -- 名稱就是這個字
        WHEN m.name ILIKE $4::text || '%' THEN 1          -- 名稱開頭命中
        WHEN m.name ILIKE '%' || $4::text || '%' THEN 2   -- 名稱中間命中
        WHEN (
            m.name || ' ' || m.reward_desc || ' ' ||
            coalesce(m.reward_desc_en, '') || ' ' || coalesce(m.reward_desc_ja, '')
        ) ILIKE '%' || $4::text || '%'
          OR (
            c.name || ' ' || coalesce(c.name_en, '') || ' ' || coalesce(c.name_ja, '')
        ) ILIKE '%' || $4::text || '%' THEN 3              -- 說明或分類名命中
        ELSE 4                                                            -- 名字只是「像」，靠 similarity 撈回來的
    END,
    CASE
        WHEN $7::text IS NULL THEN 1
        WHEN m.countries @> ARRAY[$7::text] THEN 0  -- 在地
        WHEN cardinality(m.countries) = 0 THEN 1                           -- 不分地區
        ELSE 2                                                             -- 外地
    END,
    active_code_count DESC, m.name
LIMIT $1 OFFSET $2
`

type ListMerchantsParams struct {
	Limit         int32      `json:"limit"`
	Offset        int32      `json:"offset"`
	CategoryID    *uuid.UUID `json:"category_id"`
	Search        *string    `json:"search"`
	SearchRaw     *string    `json:"search_raw"`
	Region        *string    `json:"region"`
	ViewerCountry *string    `json:"viewer_country"`
}

type ListMerchantsRow struct {
	ID                      uuid.UUID   `json:"id"`
	Slug                    string      `json:"slug"`
	Name                    string      `json:"name"`
	CategoryID              uuid.UUID   `json:"category_id"`
	LogoUrl                 *string     `json:"logo_url"`
	SignupUrl               string      `json:"signup_url"`
	RewardDesc              string      `json:"reward_desc"`
	CodeFormatRegex         *string     `json:"code_format_regex"`
	IsActive                bool        `json:"is_active"`
	CreatedAt               time.Time   `json:"created_at"`
	UpdatedAt               time.Time   `json:"updated_at"`
	Countries               []string    `json:"countries"`
	RewardDescEn            *string     `json:"reward_desc_en"`
	RewardDescJa            *string     `json:"reward_desc_ja"`
	AllowedCodeTypes        []string    `json:"allowed_code_types"`
	DiscountCodeFormatRegex *string     `json:"discount_code_format_regex"`
	CategoryName            string      `json:"category_name"`
	CategoryNameEn          *string     `json:"category_name_en"`
	CategoryNameJa          *string     `json:"category_name_ja"`
	ActiveCodeCount         int64       `json:"active_code_count"`
	SoonestExpiresAt        interface{} `json:"soonest_expires_at"`
	TotalCount              int64       `json:"total_count"`
}

// 目錄頁：帶上每家目前有幾個可用的碼，前端才能顯示「12 個可用推薦碼」。
// soonest_expires_at 是這家最快到期的那個碼，目錄頁用它顯示倒數與分「快到期」區塊；
// 一家都沒有可用的碼時是 NULL。
//
// 兩個統計值走同一個 LATERAL，referral_codes 只掃一次。
//
// sqlc 推不出 aggregate 的 nullability，soonest_expires_at 產出來是 interface{}，
// 由 handler 收成 *time.Time。加 ::timestamptz 會讓它變成非 nullable 的 time.Time，
// 掃到 NULL（這家沒有可用的碼）直接噴錯，所以不要加。
//
// total_count 是套用 LIMIT 之前的總筆數（window function 比 LIMIT 早算），
// 搜尋頁要靠它顯示「找到 N 家」，不必為了一個數字再打一次 count 查詢。
// 分類篩選只認 id。
// 搜尋比對服務商名、獎勵說明、分類名，後兩者連 en/ja 一起比 —— 使用者記得的
// 常常是「現金回饋」「銀行」這種說明或分類的字，不是品牌名。
//
// 這兩個串接表達式要跟 00011_search.sql 的 trgm 索引寫得一模一樣，差一個空白
// 就走不到索引。改這裡一定要回去改那裡。
//
// 串起來比對的副作用是跨欄位誤中（'天 銀' 會命中 '樂天 銀行送500'），
// 但那要求查詢字串自己帶空白，真實查詢幾乎不會長那樣，換一個索引很划算。
//
// search 進來之前已經在 handler escape 過 % 與 _（見 escapeLike），
// 這裡不必再處理萬用字元。
//
// 最後那條是打錯字的救援：ILIKE 是子字串比對，'coupng' 少一個字母就一筆都不中。
//
// 用 word_similarity 而不是 similarity：後者比的是整個字串，名字帶後綴時分數
// 會被稀釋掉 —— 'amazn' 對 'Amazon Shopping' 只有 0.222，對 'Amazon' 才夠高，
// 而目錄裡的名字十家有八家帶後綴。word_similarity 是拿查詢去比對方最像的那一段，
// 同一組實測 0.667。參數順序不能反：第一個是要拿去找的詞，第二個是被找的字串。
//
// 門檻 0.5 是照現有 263 家實測出來的：典型 typo 最低的是 'coupng'→'Coupang' 的
// 0.571，抓得到；再往上一階到 pg_trgm 預設的 0.6 就會漏掉它。
//
// length >= 4 這道更重要。三個字母的查詢 trigram 太少，'pay' 在 0.5 會撈出
// Paramount+、Papa Johns、Panera Bread 這種只是開頭像的；四個字以上就乾淨了
// （bank / shop / food / card 實測都沒有多撈）。短查詢本來就容易精確命中，
// 不需要模糊救。中日文查詢通常只有兩三個字，會被這道擋掉 —— 但三連字元對中文
// 本來就切不出東西（見 SuggestMerchants 的說明），擋掉沒有損失。
//
// 比對的是 search_raw（未 escape）。word_similarity 不吃 LIKE 的萬用字元，
// 餵 escape 過的字串進去，反斜線會變成要比對的內容之一。
//
// 這條走不到 merchants_name_trgm 那個 GIN 索引（要 <% 運算子才走得到，但它的
// 門檻是 session 層級的 GUC，連線池底下設了會殘留給下一個請求），所以是全表計算。
// 263 家的規模這個代價無所謂，真的長到幾萬家再回頭換成 <% 加 set_limit。
// 地區過濾。region 是 NULL 就完全不篩 —— 匿名訪客、沒填所在地、或使用者自己
// 選了「所有地區」都走這條，官網匿名的 SSR 內容因此不會因人而異，SEO 不受影響。
//
// countries 是空陣列代表不分地區（串流、雲端這種跨國服務），任何地區都該看得到，
// 所以它要在過濾裡放行，不是被當成「哪裡都不能用」。
//
// 只篩目錄，不篩 GetMerchantBySlug：從別人分享的連結點進來的人、或搜尋引擎爬到的
// 服務商頁還是要打得開，否則跨地區分享的連結會全部變成 404。
// 地區優先是排序，跟上面的過濾是兩件事：使用者切到「所有地區」時不再過濾，
// 但在地的仍然要排前面。
// viewer_country 是 NULL（沒登入、或沒填所在地）時整個 CASE 都是 1，
// 等於退回原本的排序。
func (q *Queries) ListMerchants(ctx context.Context, arg ListMerchantsParams) ([]ListMerchantsRow, error) {
	rows, err := q.db.Query(ctx, listMerchants,
		arg.Limit,
		arg.Offset,
		arg.CategoryID,
		arg.Search,
		arg.SearchRaw,
		arg.Region,
		arg.ViewerCountry,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMerchantsRow{}
	for rows.Next() {
		var i ListMerchantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.CategoryID,
			&i.LogoUrl,
			&i.SignupUrl,
			&i.RewardDesc,
			&i.CodeFormatRegex,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Countries,
			&i.RewardDescEn,
			&i.RewardDescJa,
			&i.AllowedCodeTypes,
			&i.DiscountCodeFormatRegex,
			&i.CategoryName,
			&i.CategoryNameEn,
			&i.CategoryNameJa,
			&i.ActiveCodeCount,
			&i.SoonestExpiresAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMerchantsForAdmin = `-- name: ListMerchantsForAdmin :many
SELECT
    m.id, m.slug, m.name, m.category_id, m.logo_url, m.signup_url, m.reward_desc, m.code_format_regex, m.is_active, m.created_at, m.updated_at, m.countries, m.reward_desc_en, m.reward_desc_ja, m.allowed_code_types, m.discount_code_format_regex,
    c.name AS category_name,
    (SELECT count(*) FROM referral_code_bonus.referral_codes rc
      WHERE rc.merchant_id = m.id AND rc.status = 'active'
        AND (rc.expires_at IS NULL OR rc.expires_at > now())) AS active_code_count
FROM referral_code_bonus.merchants m
JOIN referral_code_bonus.merchant_categories c ON c.id = m.category_id
ORDER BY m.name
`

type ListMerchantsForAdminRow struct {
	ID                      uuid.UUID `json:"id"`
	Slug                    string    `json:"slug"`
	Name                    string    `json:"name"`
	CategoryID              uuid.UUID `json:"category_id"`
	LogoUrl                 *string   `json:"logo_url"`
	SignupUrl               string    `json:"signup_url"`
	RewardDesc              string    `json:"reward_desc"`
	CodeFormatRegex         *string   `json:"code_format_regex"`
	IsActive                bool      `json:"is_active"`
	CreatedAt               time.Time `json:"created_at"`
	UpdatedAt               time.Time `json:"updated_at"`
	Countries               []string  `json:"countries"`
	RewardDescEn            *string   `json:"reward_desc_en"`
	RewardDescJa            *string   `json:"reward_desc_ja"`
	AllowedCodeTypes        []string  `json:"allowed_code_types"`
	DiscountCodeFormatRegex *string   `json:"discount_code_format_regex"`
	CategoryName            string    `json:"category_name"`
	ActiveCodeCount         int64     `json:"active_code_count"`
}

// 後台維護用：不過濾 is_active，而且要帶齊編輯表單需要的欄位
// （公開的 ListMerchants 只回展示用的子集）。
func (q *Queries) ListMerchantsForAdmin(ctx context.Context) ([]ListMerchantsForAdminRow, error) {
	rows, err := q.db.Query(ctx, listMerchantsForAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMerchantsForAdminRow{}
	for rows.Next() {
		var i ListMerchantsForAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.CategoryID,
			&i.LogoUrl,
			&i.SignupUrl,
			&i.RewardDesc,
			&i.CodeFormatRegex,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Countries,
			&i.RewardDescEn,
			&i.RewardDescJa,
			&i.AllowedCodeTypes,
			&i.DiscountCodeFormatRegex,
			&i.CategoryName,
			&i.ActiveCodeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMerchantsWithoutLogo = `-- name: ListMerchantsWithoutLogo :many
SELECT id, slug, name, signup_url FROM referral_code_bonus.merchants
WHERE is_active AND logo_url IS NULL ORDER BY name
`

type ListMerchantsWithoutLogoRow struct {
	ID        uuid.UUID `json:"id"`
	Slug      string    `json:"slug"`
	Name      string    `json:"name"`
	SignupUrl string    `json:"signup_url"`
}

// 補圖用：還沒有 logo 的啟用中服務商。
func (q *Queries) ListMerchantsWithoutLogo(ctx context.Context) ([]ListMerchantsWithoutLogoRow, error) {
	rows, err := q.db.Query(ctx, listMerchantsWithoutLogo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMerchantsWithoutLogoRow{}
	for rows.Next() {
		var i ListMerchantsWithoutLogoRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.SignupUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMerchantLogo = `-- name: SetMerchantLogo :execrows
UPDATE referral_code_bonus.merchants
SET logo_url = $1, updated_at = now()
WHERE id = $2 AND logo_url IS NULL
`

type SetMerchantLogoParams struct {
	LogoUrl *string   `json:"logo_url"`
	ID      uuid.UUID `json:"id"`
}

// logo 補圖用（cmd/logobackfill）。只動 logo_url，不像 UpdateMerchant 那樣整列覆蓋 ——
// 補圖跟後台編輯是兩件事，用全欄位更新會把後台剛改好的欄位一起蓋回舊值。
// 只補還沒有圖的，重複跑不會覆蓋已經有圖的（包含後台手動換過的）。
func (q *Queries) SetMerchantLogo(ctx context.Context, arg SetMerchantLogoParams) (int64, error) {
	result, err := q.db.Exec(ctx, setMerchantLogo, arg.LogoUrl, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const suggestMerchants = `-- name: SuggestMerchants :many
SELECT m.slug, m.name
FROM referral_code_bonus.merchants m
WHERE m.is_active
  AND extensions.similarity(m.name, $1::text) >= 0.15
  AND (
    $2::text IS NULL
    OR cardinality(m.countries) = 0
    OR m.countries @> ARRAY[$2::text]
  )
ORDER BY extensions.similarity(m.name, $1::text) DESC, m.name
LIMIT $3::int
`

type SuggestMerchantsParams struct {
	Search     string  `json:"search"`
	Region     *string `json:"region"`
	MaxResults int32   `json:"max_results"`
}

type SuggestMerchantsRow struct {
	Slug string `json:"slug"`
	Name string `json:"name"`
}

// 搜不到東西時的「你是不是要找 xxx」。只比服務商名 —— 建議要給得出一個
// 可以直接點進去的對象，說明或分類名相近沒辦法變成一個連結。
//
// 門檻 0.15：pg_trgm 預設的 0.3 是給整句英文用的，2-4 個字的品牌名打錯一個字
// 就掉到 0.3 以下，等於整個建議功能不會出現。0.15 是先放寬到「還看得出關聯」
// 的起點，等真實查詢累積起來再照 search_terms 裡搜不到的詞回頭調。
//
// 中日文的效果本來就比英數字差（三連字元切中文詞切不出幾個組合），
// 這條路對「rakuen → Rakuten」有效，對「台心 → 台新」幫助有限。
// 地區過濾必須跟 ListMerchants 用同一套規則。少了這段，主查詢把一家服務商
// 篩掉之後建議卻還把它推出來 —— 畫面上就是「找不到 chatgpt」的下一行寫著
// 「你是不是要找 ChatGPT」，使用者只會覺得搜尋壞了。
//
// narg 是 NULL 就不篩，理由跟 ListMerchants 那條一樣：匿名訪客、沒填所在地、
// 或自己選了「所有地區」都走這條。countries 是空陣列代表不分地區，要放行。
func (q *Queries) SuggestMerchants(ctx context.Context, arg SuggestMerchantsParams) ([]SuggestMerchantsRow, error) {
	rows, err := q.db.Query(ctx, suggestMerchants, arg.Search, arg.Region, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SuggestMerchantsRow{}
	for rows.Next() {
		var i SuggestMerchantsRow
		if err := rows.Scan(&i.Slug, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE referral_code_bonus.merchant_categories
SET name = $2, sort_order = $3, image_url = $4, name_en = $5, name_ja = $6
WHERE id = $1
RETURNING id, name, sort_order, created_at, image_url, name_en, name_ja
`

type UpdateCategoryParams struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	SortOrder int32     `json:"sort_order"`
	ImageUrl  *string   `json:"image_url"`
	NameEn    *string   `json:"name_en"`
	NameJa    *string   `json:"name_ja"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (MerchantCategory, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ID,
		arg.Name,
		arg.SortOrder,
		arg.ImageUrl,
		arg.NameEn,
		arg.NameJa,
	)
	var i MerchantCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
		&i.ImageUrl,
		&i.NameEn,
		&i.NameJa,
	)
	return i, err
}

const updateMerchant = `-- name: UpdateMerchant :one
UPDATE referral_code_bonus.merchants
SET slug = $2, name = $3, category_id = $4, logo_url = $5, signup_url = $6,
    reward_desc = $7, code_format_regex = $8, is_active = $9, countries = $10,
    reward_desc_en = $11, reward_desc_ja = $12,
    allowed_code_types = $13, discount_code_format_regex = $14, updated_at = now()
WHERE id = $1
RETURNING id, slug, name, category_id, logo_url, signup_url, reward_desc, code_format_regex, is_active, created_at, updated_at, countries, reward_desc_en, reward_desc_ja, allowed_code_types, discount_code_format_regex
`

type UpdateMerchantParams struct {
	ID                      uuid.UUID `json:"id"`
	Slug                    string    `json:"slug"`
	Name                    string    `json:"name"`
	CategoryID              uuid.UUID `json:"category_id"`
	LogoUrl                 *string   `json:"logo_url"`
	SignupUrl               string    `json:"signup_url"`
	RewardDesc              string    `json:"reward_desc"`
	CodeFormatRegex         *string   `json:"code_format_regex"`
	IsActive                bool      `json:"is_active"`
	Countries               []string  `json:"countries"`
	RewardDescEn            *string   `json:"reward_desc_en"`
	RewardDescJa            *string   `json:"reward_desc_ja"`
	AllowedCodeTypes        []string  `json:"allowed_code_types"`
	DiscountCodeFormatRegex *string   `json:"discount_code_format_regex"`
}

func (q *Queries) UpdateMerchant(ctx context.Context, arg UpdateMerchantParams) (Merchant, error) {
	row := q.db.QueryRow(ctx, updateMerchant,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.CategoryID,
		arg.LogoUrl,
		arg.SignupUrl,
		arg.RewardDesc,
		arg.CodeFormatRegex,
		arg.IsActive,
		arg.Countries,
		arg.RewardDescEn,
		arg.RewardDescJa,
		arg.AllowedCodeTypes,
		arg.DiscountCodeFormatRegex,
	)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CategoryID,
		&i.LogoUrl,
		&i.SignupUrl,
		&i.RewardDesc,
		&i.CodeFormatRegex,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Countries,
		&i.RewardDescEn,
		&i.RewardDescJa,
		&i.AllowedCodeTypes,
		&i.DiscountCodeFormatRegex,
	)
	return i, err
}
