// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: merchants.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO referral_code_bonus.merchant_categories (name, sort_order, image_url)
VALUES ($1, $2, $3)
RETURNING id, name, sort_order, created_at, image_url
`

type CreateCategoryParams struct {
	Name      string  `json:"name"`
	SortOrder int32   `json:"sort_order"`
	ImageUrl  *string `json:"image_url"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (MerchantCategory, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.Name, arg.SortOrder, arg.ImageUrl)
	var i MerchantCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
		&i.ImageUrl,
	)
	return i, err
}

const createMerchant = `-- name: CreateMerchant :one
INSERT INTO referral_code_bonus.merchants (slug, name, category_id, logo_url, signup_url, reward_desc, code_format_regex, countries)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, slug, name, category_id, logo_url, signup_url, reward_desc, code_format_regex, is_active, created_at, updated_at, countries
`

type CreateMerchantParams struct {
	Slug            string    `json:"slug"`
	Name            string    `json:"name"`
	CategoryID      uuid.UUID `json:"category_id"`
	LogoUrl         *string   `json:"logo_url"`
	SignupUrl       string    `json:"signup_url"`
	RewardDesc      string    `json:"reward_desc"`
	CodeFormatRegex *string   `json:"code_format_regex"`
	Countries       []string  `json:"countries"`
}

func (q *Queries) CreateMerchant(ctx context.Context, arg CreateMerchantParams) (Merchant, error) {
	row := q.db.QueryRow(ctx, createMerchant,
		arg.Slug,
		arg.Name,
		arg.CategoryID,
		arg.LogoUrl,
		arg.SignupUrl,
		arg.RewardDesc,
		arg.CodeFormatRegex,
		arg.Countries,
	)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CategoryID,
		&i.LogoUrl,
		&i.SignupUrl,
		&i.RewardDesc,
		&i.CodeFormatRegex,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Countries,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM referral_code_bonus.merchant_categories WHERE id = $1
`

// merchants.category_id 是 FK 且沒有 ON DELETE，還有服務商掛著的分類刪不掉，
// 交給呼叫端把 23503 轉成看得懂的錯誤（見 store.IsForeignKeyViolation）。
func (q *Queries) DeleteCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCategory, id)
	return err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, name, sort_order, created_at, image_url FROM referral_code_bonus.merchant_categories WHERE id = $1
`

func (q *Queries) GetCategoryByID(ctx context.Context, id uuid.UUID) (MerchantCategory, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i MerchantCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
		&i.ImageUrl,
	)
	return i, err
}

const getMerchantByID = `-- name: GetMerchantByID :one
SELECT id, slug, name, category_id, logo_url, signup_url, reward_desc, code_format_regex, is_active, created_at, updated_at, countries FROM referral_code_bonus.merchants WHERE id = $1
`

func (q *Queries) GetMerchantByID(ctx context.Context, id uuid.UUID) (Merchant, error) {
	row := q.db.QueryRow(ctx, getMerchantByID, id)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CategoryID,
		&i.LogoUrl,
		&i.SignupUrl,
		&i.RewardDesc,
		&i.CodeFormatRegex,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Countries,
	)
	return i, err
}

const getMerchantBySlug = `-- name: GetMerchantBySlug :one
SELECT m.id, m.slug, m.name, m.category_id, m.logo_url, m.signup_url, m.reward_desc, m.code_format_regex, m.is_active, m.created_at, m.updated_at, m.countries, c.name AS category_name
FROM referral_code_bonus.merchants m
JOIN referral_code_bonus.merchant_categories c ON c.id = m.category_id
WHERE m.slug = $1 AND m.is_active
`

type GetMerchantBySlugRow struct {
	ID              uuid.UUID `json:"id"`
	Slug            string    `json:"slug"`
	Name            string    `json:"name"`
	CategoryID      uuid.UUID `json:"category_id"`
	LogoUrl         *string   `json:"logo_url"`
	SignupUrl       string    `json:"signup_url"`
	RewardDesc      string    `json:"reward_desc"`
	CodeFormatRegex *string   `json:"code_format_regex"`
	IsActive        bool      `json:"is_active"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	Countries       []string  `json:"countries"`
	CategoryName    string    `json:"category_name"`
}

func (q *Queries) GetMerchantBySlug(ctx context.Context, slug string) (GetMerchantBySlugRow, error) {
	row := q.db.QueryRow(ctx, getMerchantBySlug, slug)
	var i GetMerchantBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CategoryID,
		&i.LogoUrl,
		&i.SignupUrl,
		&i.RewardDesc,
		&i.CodeFormatRegex,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Countries,
		&i.CategoryName,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, sort_order, created_at, image_url FROM referral_code_bonus.merchant_categories ORDER BY sort_order, name
`

func (q *Queries) ListCategories(ctx context.Context) ([]MerchantCategory, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MerchantCategory{}
	for rows.Next() {
		var i MerchantCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SortOrder,
			&i.CreatedAt,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMerchantSlugs = `-- name: ListMerchantSlugs :many
SELECT slug, updated_at FROM referral_code_bonus.merchants WHERE is_active ORDER BY slug
`

type ListMerchantSlugsRow struct {
	Slug      string    `json:"slug"`
	UpdatedAt time.Time `json:"updated_at"`
}

// sitemap 用：所有可索引的服務商 slug。
func (q *Queries) ListMerchantSlugs(ctx context.Context) ([]ListMerchantSlugsRow, error) {
	rows, err := q.db.Query(ctx, listMerchantSlugs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMerchantSlugsRow{}
	for rows.Next() {
		var i ListMerchantSlugsRow
		if err := rows.Scan(&i.Slug, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMerchants = `-- name: ListMerchants :many
SELECT
    m.id, m.slug, m.name, m.category_id, m.logo_url, m.signup_url, m.reward_desc, m.code_format_regex, m.is_active, m.created_at, m.updated_at, m.countries,
    c.name AS category_name,
    coalesce(stat.active_code_count, 0) AS active_code_count,
    stat.soonest_expires_at
FROM referral_code_bonus.merchants m
JOIN referral_code_bonus.merchant_categories c ON c.id = m.category_id
LEFT JOIN LATERAL (
    SELECT count(*) AS active_code_count, min(rc.expires_at) AS soonest_expires_at
    FROM referral_code_bonus.referral_codes rc
    WHERE rc.merchant_id = m.id AND rc.status = 'active' AND rc.expires_at > now()
) stat ON true
WHERE m.is_active
  AND ($3::uuid IS NULL OR m.category_id = $3::uuid)
  AND ($4::text IS NULL OR m.name ILIKE '%' || $4::text || '%')
ORDER BY
    CASE
        WHEN $5::text IS NULL THEN 1
        WHEN m.countries @> ARRAY[$5::text] THEN 0  -- 在地
        WHEN cardinality(m.countries) = 0 THEN 1                           -- 不分地區
        ELSE 2                                                             -- 外地
    END,
    active_code_count DESC, m.name
LIMIT $1 OFFSET $2
`

type ListMerchantsParams struct {
	Limit         int32      `json:"limit"`
	Offset        int32      `json:"offset"`
	CategoryID    *uuid.UUID `json:"category_id"`
	Search        *string    `json:"search"`
	ViewerCountry *string    `json:"viewer_country"`
}

type ListMerchantsRow struct {
	ID               uuid.UUID   `json:"id"`
	Slug             string      `json:"slug"`
	Name             string      `json:"name"`
	CategoryID       uuid.UUID   `json:"category_id"`
	LogoUrl          *string     `json:"logo_url"`
	SignupUrl        string      `json:"signup_url"`
	RewardDesc       string      `json:"reward_desc"`
	CodeFormatRegex  *string     `json:"code_format_regex"`
	IsActive         bool        `json:"is_active"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
	Countries        []string    `json:"countries"`
	CategoryName     string      `json:"category_name"`
	ActiveCodeCount  int64       `json:"active_code_count"`
	SoonestExpiresAt interface{} `json:"soonest_expires_at"`
}

// 目錄頁：帶上每家目前有幾個可用的碼，前端才能顯示「12 個可用推薦碼」。
// soonest_expires_at 是這家最快到期的那個碼，目錄頁用它顯示倒數與分「快到期」區塊；
// 一家都沒有可用的碼時是 NULL。
//
// 兩個統計值走同一個 LATERAL，referral_codes 只掃一次。
//
// sqlc 推不出 aggregate 的 nullability，soonest_expires_at 產出來是 interface{}，
// 由 handler 收成 *time.Time。加 ::timestamptz 會讓它變成非 nullable 的 time.Time，
// 掃到 NULL（這家沒有可用的碼）直接噴錯，所以不要加。
// 分類篩選只認 id。
// 地區優先只是排序，不過濾：外地的服務商照樣看得到，只是排在後面。
// viewer_country 是 NULL（沒登入、或沒填所在地）時整個 CASE 都是 1，
// 等於退回原本的排序 —— 匿名訪客拿到的 SSR 內容不會因人而異，SEO 才不會受影響。
func (q *Queries) ListMerchants(ctx context.Context, arg ListMerchantsParams) ([]ListMerchantsRow, error) {
	rows, err := q.db.Query(ctx, listMerchants,
		arg.Limit,
		arg.Offset,
		arg.CategoryID,
		arg.Search,
		arg.ViewerCountry,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMerchantsRow{}
	for rows.Next() {
		var i ListMerchantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.CategoryID,
			&i.LogoUrl,
			&i.SignupUrl,
			&i.RewardDesc,
			&i.CodeFormatRegex,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Countries,
			&i.CategoryName,
			&i.ActiveCodeCount,
			&i.SoonestExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMerchantsForAdmin = `-- name: ListMerchantsForAdmin :many
SELECT
    m.id, m.slug, m.name, m.category_id, m.logo_url, m.signup_url, m.reward_desc, m.code_format_regex, m.is_active, m.created_at, m.updated_at, m.countries,
    c.name AS category_name,
    (SELECT count(*) FROM referral_code_bonus.referral_codes rc
      WHERE rc.merchant_id = m.id AND rc.status = 'active' AND rc.expires_at > now()) AS active_code_count
FROM referral_code_bonus.merchants m
JOIN referral_code_bonus.merchant_categories c ON c.id = m.category_id
ORDER BY m.name
`

type ListMerchantsForAdminRow struct {
	ID              uuid.UUID `json:"id"`
	Slug            string    `json:"slug"`
	Name            string    `json:"name"`
	CategoryID      uuid.UUID `json:"category_id"`
	LogoUrl         *string   `json:"logo_url"`
	SignupUrl       string    `json:"signup_url"`
	RewardDesc      string    `json:"reward_desc"`
	CodeFormatRegex *string   `json:"code_format_regex"`
	IsActive        bool      `json:"is_active"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	Countries       []string  `json:"countries"`
	CategoryName    string    `json:"category_name"`
	ActiveCodeCount int64     `json:"active_code_count"`
}

// 後台維護用：不過濾 is_active，而且要帶齊編輯表單需要的欄位
// （公開的 ListMerchants 只回展示用的子集）。
func (q *Queries) ListMerchantsForAdmin(ctx context.Context) ([]ListMerchantsForAdminRow, error) {
	rows, err := q.db.Query(ctx, listMerchantsForAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMerchantsForAdminRow{}
	for rows.Next() {
		var i ListMerchantsForAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.CategoryID,
			&i.LogoUrl,
			&i.SignupUrl,
			&i.RewardDesc,
			&i.CodeFormatRegex,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Countries,
			&i.CategoryName,
			&i.ActiveCodeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE referral_code_bonus.merchant_categories
SET name = $2, sort_order = $3, image_url = $4
WHERE id = $1
RETURNING id, name, sort_order, created_at, image_url
`

type UpdateCategoryParams struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	SortOrder int32     `json:"sort_order"`
	ImageUrl  *string   `json:"image_url"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (MerchantCategory, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ID,
		arg.Name,
		arg.SortOrder,
		arg.ImageUrl,
	)
	var i MerchantCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
		&i.ImageUrl,
	)
	return i, err
}

const updateMerchant = `-- name: UpdateMerchant :one
UPDATE referral_code_bonus.merchants
SET slug = $2, name = $3, category_id = $4, logo_url = $5, signup_url = $6,
    reward_desc = $7, code_format_regex = $8, is_active = $9, countries = $10, updated_at = now()
WHERE id = $1
RETURNING id, slug, name, category_id, logo_url, signup_url, reward_desc, code_format_regex, is_active, created_at, updated_at, countries
`

type UpdateMerchantParams struct {
	ID              uuid.UUID `json:"id"`
	Slug            string    `json:"slug"`
	Name            string    `json:"name"`
	CategoryID      uuid.UUID `json:"category_id"`
	LogoUrl         *string   `json:"logo_url"`
	SignupUrl       string    `json:"signup_url"`
	RewardDesc      string    `json:"reward_desc"`
	CodeFormatRegex *string   `json:"code_format_regex"`
	IsActive        bool      `json:"is_active"`
	Countries       []string  `json:"countries"`
}

func (q *Queries) UpdateMerchant(ctx context.Context, arg UpdateMerchantParams) (Merchant, error) {
	row := q.db.QueryRow(ctx, updateMerchant,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.CategoryID,
		arg.LogoUrl,
		arg.SignupUrl,
		arg.RewardDesc,
		arg.CodeFormatRegex,
		arg.IsActive,
		arg.Countries,
	)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CategoryID,
		&i.LogoUrl,
		&i.SignupUrl,
		&i.RewardDesc,
		&i.CodeFormatRegex,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Countries,
	)
	return i, err
}
