// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"time"

	"github.com/google/uuid"
)

type Admin struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	DisplayName  string    `json:"display_name"`
	Role         string    `json:"role"`
	IsActive     bool      `json:"is_active"`
	CreatedAt    time.Time `json:"created_at"`
}

type CodeEvent struct {
	ID         uuid.UUID  `json:"id"`
	CodeID     uuid.UUID  `json:"code_id"`
	MerchantID uuid.UUID  `json:"merchant_id"`
	EventType  string     `json:"event_type"`
	UserID     *uuid.UUID `json:"user_id"`
	DeviceHash string     `json:"device_hash"`
	IpHash     string     `json:"ip_hash"`
	IsBillable bool       `json:"is_billable"`
	CreatedAt  time.Time  `json:"created_at"`
}

type CodeReport struct {
	ID         uuid.UUID  `json:"id"`
	CodeID     uuid.UUID  `json:"code_id"`
	ReporterID *uuid.UUID `json:"reporter_id"`
	DeviceHash string     `json:"device_hash"`
	Result     string     `json:"result"`
	CreatedAt  time.Time  `json:"created_at"`
}

type CodeReview struct {
	ID        uuid.UUID  `json:"id"`
	CodeID    uuid.UUID  `json:"code_id"`
	AdminID   *uuid.UUID `json:"admin_id"`
	Action    string     `json:"action"`
	Reason    string     `json:"reason"`
	CreatedAt time.Time  `json:"created_at"`
}

type Merchant struct {
	ID                      uuid.UUID `json:"id"`
	Slug                    string    `json:"slug"`
	Name                    string    `json:"name"`
	CategoryID              uuid.UUID `json:"category_id"`
	LogoUrl                 *string   `json:"logo_url"`
	SignupUrl               string    `json:"signup_url"`
	RewardDesc              string    `json:"reward_desc"`
	CodeFormatRegex         *string   `json:"code_format_regex"`
	IsActive                bool      `json:"is_active"`
	CreatedAt               time.Time `json:"created_at"`
	UpdatedAt               time.Time `json:"updated_at"`
	Countries               []string  `json:"countries"`
	RewardDescEn            *string   `json:"reward_desc_en"`
	RewardDescJa            *string   `json:"reward_desc_ja"`
	AllowedCodeTypes        []string  `json:"allowed_code_types"`
	DiscountCodeFormatRegex *string   `json:"discount_code_format_regex"`
}

type MerchantCategory struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	SortOrder int32     `json:"sort_order"`
	CreatedAt time.Time `json:"created_at"`
	ImageUrl  *string   `json:"image_url"`
	NameEn    *string   `json:"name_en"`
	NameJa    *string   `json:"name_ja"`
}

type MerchantSuggestion struct {
	ID           uuid.UUID  `json:"id"`
	UserID       uuid.UUID  `json:"user_id"`
	Name         string     `json:"name"`
	SignupUrl    string     `json:"signup_url"`
	Note         string     `json:"note"`
	Status       string     `json:"status"`
	ReviewedBy   *uuid.UUID `json:"reviewed_by"`
	ReviewedAt   *time.Time `json:"reviewed_at"`
	ReviewReason string     `json:"review_reason"`
	MerchantID   *uuid.UUID `json:"merchant_id"`
	CreatedAt    time.Time  `json:"created_at"`
}

type OAuthIdentity struct {
	ID             uuid.UUID `json:"id"`
	UserID         uuid.UUID `json:"user_id"`
	Provider       string    `json:"provider"`
	ProviderUserID string    `json:"provider_user_id"`
	CreatedAt      time.Time `json:"created_at"`
}

type ReferralCode struct {
	ID           uuid.UUID  `json:"id"`
	UserID       uuid.UUID  `json:"user_id"`
	MerchantID   uuid.UUID  `json:"merchant_id"`
	Code         string     `json:"code"`
	Note         string     `json:"note"`
	Status       string     `json:"status"`
	ExpiresAt    *time.Time `json:"expires_at"`
	QualityScore int32      `json:"quality_score"`
	Impressions  int64      `json:"impressions"`
	CreatedAt    time.Time  `json:"created_at"`
	ActivatedAt  *time.Time `json:"activated_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
	CodeType     string     `json:"code_type"`
}

type ReferralCodeBonusUserBlock struct {
	BlockerID uuid.UUID `json:"blocker_id"`
	BlockedID uuid.UUID `json:"blocked_id"`
	CreatedAt time.Time `json:"created_at"`
}

type RefreshToken struct {
	ID        uuid.UUID  `json:"id"`
	UserID    uuid.UUID  `json:"user_id"`
	TokenHash string     `json:"token_hash"`
	FamilyID  uuid.UUID  `json:"family_id"`
	ExpiresAt time.Time  `json:"expires_at"`
	RotatedAt *time.Time `json:"rotated_at"`
	RevokedAt *time.Time `json:"revoked_at"`
	UserAgent string     `json:"user_agent"`
	CreatedAt time.Time  `json:"created_at"`
}

type SearchTerm struct {
	Term           string    `json:"term"`
	Lang           string    `json:"lang"`
	Hits           int64     `json:"hits"`
	LastSearchedAt time.Time `json:"last_searched_at"`
}

type Subscription struct {
	UserID      uuid.UUID  `json:"user_id"`
	Entitlement string     `json:"entitlement"`
	ProductID   string     `json:"product_id"`
	Store       string     `json:"store"`
	IsActive    bool       `json:"is_active"`
	WillRenew   bool       `json:"will_renew"`
	ExpiresAt   *time.Time `json:"expires_at"`
	RcAppUserID string     `json:"rc_app_user_id"`
	UpdatedAt   time.Time  `json:"updated_at"`
}

type SubscriptionEvent struct {
	ID        uuid.UUID  `json:"id"`
	RcEventID string     `json:"rc_event_id"`
	UserID    *uuid.UUID `json:"user_id"`
	EventType string     `json:"event_type"`
	Payload   []byte     `json:"payload"`
	CreatedAt time.Time  `json:"created_at"`
}

type User struct {
	ID              uuid.UUID  `json:"id"`
	Email           string     `json:"email"`
	EmailVerifiedAt *time.Time `json:"email_verified_at"`
	DisplayName     string     `json:"display_name"`
	AvatarUrl       *string    `json:"avatar_url"`
	PasswordHash    *string    `json:"password_hash"`
	Status          string     `json:"status"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
	Country         *string    `json:"country"`
	AvatarPublicID  *string    `json:"avatar_public_id"`
}
