// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scheduled_jobs.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimDueJob = `-- name: ClaimDueJob :one
WITH due AS (
    SELECT s.name AS due_name, (s.run_requested_at IS NOT NULL)::boolean AS manual
    FROM referral_code_bonus.scheduled_jobs s
    WHERE s.name = $1
      AND s.enabled
      AND (
          -- 後台按了「立即執行」就不管間隔
          s.run_requested_at IS NOT NULL
          -- 從沒跑過（剛加進來的 job）
          OR s.last_run_at IS NULL
          OR s.last_run_at + make_interval(secs => s.interval_seconds) <= now()
      )
    FOR UPDATE SKIP LOCKED
)
UPDATE referral_code_bonus.scheduled_jobs j
SET last_run_at = now(),
    run_requested_at = NULL,
    updated_at = now()
FROM due
WHERE j.name = due.due_name
RETURNING due.manual
`

// 認領一支到期的 job。回一列代表「這個 instance 拿到了，可以跑」，回 no rows
// 代表還沒到期、被關掉、或被別的 instance 搶走了。
//
// 認領與更新 last_run_at 是同一個 statement，所以兩個 instance 同時醒來只有一個
// 拿得到 —— 沒有這層的話，Northflank 上擴到兩個 replica 就會同時去爬同一批網址。
// SKIP LOCKED 讓搶輸的那個立刻拿到 no rows 而不是卡著等。
//
// 要用 CTE 是因為 RETURNING 看到的是更新後的列：run_requested_at 在 SET 裡被清成
// NULL，直接 RETURNING 判斷永遠會是 false，分不出這輪是排程還是後台按的。
// CTE 的輸出欄位不能也叫 name：UPDATE ... FROM due 之後 due 與被更新的
// scheduled_jobs 在同一個 scope 裡，sqlc 解析 @name 時會判成 ambiguous。
// ::boolean 的 cast 也不能省，不然 manual 會被推成 interface{}。
func (q *Queries) ClaimDueJob(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRow(ctx, claimDueJob, name)
	var manual bool
	err := row.Scan(&manual)
	return manual, err
}

const deleteOldJobRuns = `-- name: DeleteOldJobRuns :execrows
DELETE FROM referral_code_bonus.job_runs
WHERE started_at < now() - make_interval(days => $1::int)
`

// 執行紀錄是診斷用的，留一段時間就好。按天數清而不是「每支留 N 筆」：
// 後者要 window function，而 sqlc 看不到 derived table 的 rn 欄位。
func (q *Queries) DeleteOldJobRuns(ctx context.Context, keepDays int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldJobRuns, keepDays)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failStaleJobRuns = `-- name: FailStaleJobRuns :execrows
UPDATE referral_code_bonus.job_runs
SET status = 'failed',
    error = '服務重啟，這輪沒有正常結束',
    finished_at = now()
WHERE status = 'running' AND started_at < $1
`

// 啟動時把上一個 process 留下的 running 收乾淨。API 被硬殺（部署、OOM）時，
// FinishJobRun 沒機會跑，那列會永遠停在 running，後台看起來像「還在跑」。
//
// 只收「這次啟動之前就開始」的，不然多 instance 情況下會把別人正在跑的那列
// 標成失敗。
func (q *Queries) FailStaleJobRuns(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, failStaleJobRuns, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishJobRun = `-- name: FinishJobRun :exec
UPDATE referral_code_bonus.job_runs
SET status = $1, summary = $2, error = $3, finished_at = now()
WHERE id = $4
`

type FinishJobRunParams struct {
	Status  string    `json:"status"`
	Summary string    `json:"summary"`
	Error   string    `json:"error"`
	ID      uuid.UUID `json:"id"`
}

func (q *Queries) FinishJobRun(ctx context.Context, arg FinishJobRunParams) error {
	_, err := q.db.Exec(ctx, finishJobRun,
		arg.Status,
		arg.Summary,
		arg.Error,
		arg.ID,
	)
	return err
}

const listJobRuns = `-- name: ListJobRuns :many
SELECT id, job_name, started_at, finished_at, status, summary, error, trigger FROM referral_code_bonus.job_runs
WHERE job_name = $1
ORDER BY started_at DESC
LIMIT $2
`

type ListJobRunsParams struct {
	JobName  string `json:"job_name"`
	RowLimit int32  `json:"row_limit"`
}

func (q *Queries) ListJobRuns(ctx context.Context, arg ListJobRunsParams) ([]JobRun, error) {
	rows, err := q.db.Query(ctx, listJobRuns, arg.JobName, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobRun{}
	for rows.Next() {
		var i JobRun
		if err := rows.Scan(
			&i.ID,
			&i.JobName,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.Summary,
			&i.Error,
			&i.Trigger,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobs = `-- name: ListJobs :many
SELECT
    j.name, j.enabled, j.interval_seconds, j.last_run_at, j.run_requested_at,
    j.interval_overridden, j.updated_at,
    coalesce(lr.status, '') AS last_status,
    coalesce(lr.summary, '') AS last_summary,
    coalesce(lr.error, '') AS last_error,
    lr.finished_at AS last_finished_at
FROM referral_code_bonus.scheduled_jobs j
LEFT JOIN LATERAL (
    SELECT r.status, r.summary, r.error, r.finished_at
    FROM referral_code_bonus.job_runs r
    WHERE r.job_name = j.name
    ORDER BY r.started_at DESC
    LIMIT 1
) lr ON true
ORDER BY j.name
`

type ListJobsRow struct {
	Name               string     `json:"name"`
	Enabled            bool       `json:"enabled"`
	IntervalSeconds    int32      `json:"interval_seconds"`
	LastRunAt          *time.Time `json:"last_run_at"`
	RunRequestedAt     *time.Time `json:"run_requested_at"`
	IntervalOverridden bool       `json:"interval_overridden"`
	UpdatedAt          time.Time  `json:"updated_at"`
	LastStatus         string     `json:"last_status"`
	LastSummary        string     `json:"last_summary"`
	LastError          string     `json:"last_error"`
	LastFinishedAt     *time.Time `json:"last_finished_at"`
}

// 後台的排程列表，帶最近一次執行的結果。
// 別名不用 last：那是 SQL 關鍵字，sqlc 的 parser 會把 last.status 解析壞掉。
func (q *Queries) ListJobs(ctx context.Context) ([]ListJobsRow, error) {
	rows, err := q.db.Query(ctx, listJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJobsRow{}
	for rows.Next() {
		var i ListJobsRow
		if err := rows.Scan(
			&i.Name,
			&i.Enabled,
			&i.IntervalSeconds,
			&i.LastRunAt,
			&i.RunRequestedAt,
			&i.IntervalOverridden,
			&i.UpdatedAt,
			&i.LastStatus,
			&i.LastSummary,
			&i.LastError,
			&i.LastFinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requestJobRun = `-- name: RequestJobRun :one
UPDATE referral_code_bonus.scheduled_jobs
SET run_requested_at = now(), updated_at = now()
WHERE name = $1 AND enabled
RETURNING name, enabled, interval_seconds, last_run_at, run_requested_at, interval_overridden, created_at, updated_at
`

// 後台按「立即執行」。只是留一個記號，真正跑起來是下一次輪詢時 ClaimDueJob 認領到
// —— HTTP handler 不該等一支爬蟲跑完。
func (q *Queries) RequestJobRun(ctx context.Context, name string) (ScheduledJob, error) {
	row := q.db.QueryRow(ctx, requestJobRun, name)
	var i ScheduledJob
	err := row.Scan(
		&i.Name,
		&i.Enabled,
		&i.IntervalSeconds,
		&i.LastRunAt,
		&i.RunRequestedAt,
		&i.IntervalOverridden,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setJobEnabled = `-- name: SetJobEnabled :one
UPDATE referral_code_bonus.scheduled_jobs
SET enabled = $1, updated_at = now()
WHERE name = $2
RETURNING name, enabled, interval_seconds, last_run_at, run_requested_at, interval_overridden, created_at, updated_at
`

type SetJobEnabledParams struct {
	Enabled bool   `json:"enabled"`
	Name    string `json:"name"`
}

func (q *Queries) SetJobEnabled(ctx context.Context, arg SetJobEnabledParams) (ScheduledJob, error) {
	row := q.db.QueryRow(ctx, setJobEnabled, arg.Enabled, arg.Name)
	var i ScheduledJob
	err := row.Scan(
		&i.Name,
		&i.Enabled,
		&i.IntervalSeconds,
		&i.LastRunAt,
		&i.RunRequestedAt,
		&i.IntervalOverridden,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setJobInterval = `-- name: SetJobInterval :one
UPDATE referral_code_bonus.scheduled_jobs
SET interval_seconds = $1,
    interval_overridden = true,
    updated_at = now()
WHERE name = $2
RETURNING name, enabled, interval_seconds, last_run_at, run_requested_at, interval_overridden, created_at, updated_at
`

type SetJobIntervalParams struct {
	IntervalSeconds int32  `json:"interval_seconds"`
	Name            string `json:"name"`
}

// 標記 interval_overridden，之後部署不會把這個值蓋回程式裡的預設。
func (q *Queries) SetJobInterval(ctx context.Context, arg SetJobIntervalParams) (ScheduledJob, error) {
	row := q.db.QueryRow(ctx, setJobInterval, arg.IntervalSeconds, arg.Name)
	var i ScheduledJob
	err := row.Scan(
		&i.Name,
		&i.Enabled,
		&i.IntervalSeconds,
		&i.LastRunAt,
		&i.RunRequestedAt,
		&i.IntervalOverridden,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const startJobRun = `-- name: StartJobRun :one
INSERT INTO referral_code_bonus.job_runs (job_name, trigger)
VALUES ($1, $2)
RETURNING id, job_name, started_at, finished_at, status, summary, error, trigger
`

type StartJobRunParams struct {
	JobName string `json:"job_name"`
	Trigger string `json:"trigger"`
}

func (q *Queries) StartJobRun(ctx context.Context, arg StartJobRunParams) (JobRun, error) {
	row := q.db.QueryRow(ctx, startJobRun, arg.JobName, arg.Trigger)
	var i JobRun
	err := row.Scan(
		&i.ID,
		&i.JobName,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.Summary,
		&i.Error,
		&i.Trigger,
	)
	return i, err
}

const upsertJob = `-- name: UpsertJob :exec
INSERT INTO referral_code_bonus.scheduled_jobs (name, interval_seconds)
VALUES ($1, $2)
ON CONFLICT (name) DO UPDATE
SET interval_seconds = CASE
        WHEN referral_code_bonus.scheduled_jobs.interval_overridden
            THEN referral_code_bonus.scheduled_jobs.interval_seconds
            ELSE EXCLUDED.interval_seconds
    END,
    updated_at = now()
`

type UpsertJobParams struct {
	Name            string `json:"name"`
	IntervalSeconds int32  `json:"interval_seconds"`
}

// worker 啟動時把程式裡註冊的每支 job 補進表裡。已經有的列不動 enabled 與
// last_run_at —— 那是後台跟執行歷程的狀態，部署一次就被重設的話，「先關掉這支」
// 會在下一次部署自己打開。
//
// interval_seconds 只在沒被人改過時跟著程式走：改預設值要能發下去，但後台調過
// 的那些不該被蓋回去，兩件事靠 interval_overridden 分開。
func (q *Queries) UpsertJob(ctx context.Context, arg UpsertJobParams) error {
	_, err := q.db.Exec(ctx, upsertJob, arg.Name, arg.IntervalSeconds)
	return err
}
