// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package dbgen

import (
	"context"
)

const listPopularSearchTerms = `-- name: ListPopularSearchTerms :many
SELECT term, hits
FROM referral_code_bonus.search_terms
WHERE lang = $1::text
  AND last_searched_at > now() - $2::int * interval '1 day'
ORDER BY hits DESC, term
LIMIT $3::int
`

type ListPopularSearchTermsParams struct {
	Lang       string `json:"lang"`
	WindowDays int32  `json:"window_days"`
	MaxResults int32  `json:"max_results"`
}

type ListPopularSearchTermsRow struct {
	Term string `json:"term"`
	Hits int64  `json:"hits"`
}

// 榜單只看最近這段時間有人搜過的詞。不設時間窗的話，早期洗上去的詞會永遠卡在
// 前面，新的熱門服務商永遠擠不進來。
func (q *Queries) ListPopularSearchTerms(ctx context.Context, arg ListPopularSearchTermsParams) ([]ListPopularSearchTermsRow, error) {
	rows, err := q.db.Query(ctx, listPopularSearchTerms, arg.Lang, arg.WindowDays, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPopularSearchTermsRow{}
	for rows.Next() {
		var i ListPopularSearchTermsRow
		if err := rows.Scan(&i.Term, &i.Hits); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSearchTerm = `-- name: UpsertSearchTerm :exec
INSERT INTO referral_code_bonus.search_terms (term, lang)
VALUES ($1::text, $2::text)
ON CONFLICT (term, lang) DO UPDATE
SET hits = referral_code_bonus.search_terms.hits + 1,
    last_searched_at = now()
`

type UpsertSearchTermParams struct {
	Term string `json:"term"`
	Lang string `json:"lang"`
}

// 熱門關鍵字。只有使用者明確送出的查詢才進來（API 的 commit 參數），
// 逐字輸入不記 —— 打一次「台新銀行」會留下四筆前綴，榜單就毀了。
func (q *Queries) UpsertSearchTerm(ctx context.Context, arg UpsertSearchTermParams) error {
	_, err := q.db.Exec(ctx, upsertSearchTerm, arg.Term, arg.Lang)
	return err
}
