// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countActiveCodesForUser = `-- name: CountActiveCodesForUser :one
SELECT count(*) FROM referral_code_bonus.referral_codes
WHERE user_id = $1 AND status IN ('pending', 'active')
`

func (q *Queries) CountActiveCodesForUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveCodesForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getActiveSubscription = `-- name: GetActiveSubscription :one
SELECT user_id, entitlement, product_id, store, is_active, will_renew, expires_at, rc_app_user_id, updated_at FROM referral_code_bonus.subscriptions
WHERE user_id = $1
  AND is_active
  AND (expires_at IS NULL OR expires_at > now())
`

// 到期日是 NULL 代表永久授權（promotional / 買斷），要當成還沒到期。
func (q *Queries) GetActiveSubscription(ctx context.Context, userID uuid.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getActiveSubscription, userID)
	var i Subscription
	err := row.Scan(
		&i.UserID,
		&i.Entitlement,
		&i.ProductID,
		&i.Store,
		&i.IsActive,
		&i.WillRenew,
		&i.ExpiresAt,
		&i.RcAppUserID,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSubscriptionEvent = `-- name: InsertSubscriptionEvent :one
INSERT INTO referral_code_bonus.subscription_events (rc_event_id, user_id, event_type, payload)
VALUES ($1, $2, $3, $4)
ON CONFLICT (rc_event_id) DO NOTHING
RETURNING id, rc_event_id, user_id, event_type, payload, created_at
`

type InsertSubscriptionEventParams struct {
	RcEventID string     `json:"rc_event_id"`
	UserID    *uuid.UUID `json:"user_id"`
	EventType string     `json:"event_type"`
	Payload   []byte     `json:"payload"`
}

// webhook 會重送，靠 rc_event_id 擋掉重複處理。
func (q *Queries) InsertSubscriptionEvent(ctx context.Context, arg InsertSubscriptionEventParams) (SubscriptionEvent, error) {
	row := q.db.QueryRow(ctx, insertSubscriptionEvent,
		arg.RcEventID,
		arg.UserID,
		arg.EventType,
		arg.Payload,
	)
	var i SubscriptionEvent
	err := row.Scan(
		&i.ID,
		&i.RcEventID,
		&i.UserID,
		&i.EventType,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const upsertSubscription = `-- name: UpsertSubscription :one
INSERT INTO referral_code_bonus.subscriptions (
    user_id, entitlement, product_id, store, is_active, will_renew, expires_at, rc_app_user_id, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, now())
ON CONFLICT (user_id) DO UPDATE SET
    entitlement    = EXCLUDED.entitlement,
    product_id     = EXCLUDED.product_id,
    store          = EXCLUDED.store,
    is_active      = EXCLUDED.is_active,
    will_renew     = EXCLUDED.will_renew,
    expires_at     = EXCLUDED.expires_at,
    rc_app_user_id = EXCLUDED.rc_app_user_id,
    updated_at     = now()
RETURNING user_id, entitlement, product_id, store, is_active, will_renew, expires_at, rc_app_user_id, updated_at
`

type UpsertSubscriptionParams struct {
	UserID      uuid.UUID  `json:"user_id"`
	Entitlement string     `json:"entitlement"`
	ProductID   string     `json:"product_id"`
	Store       string     `json:"store"`
	IsActive    bool       `json:"is_active"`
	WillRenew   bool       `json:"will_renew"`
	ExpiresAt   *time.Time `json:"expires_at"`
	RcAppUserID string     `json:"rc_app_user_id"`
}

func (q *Queries) UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, upsertSubscription,
		arg.UserID,
		arg.Entitlement,
		arg.ProductID,
		arg.Store,
		arg.IsActive,
		arg.WillRenew,
		arg.ExpiresAt,
		arg.RcAppUserID,
	)
	var i Subscription
	err := row.Scan(
		&i.UserID,
		&i.Entitlement,
		&i.ProductID,
		&i.Store,
		&i.IsActive,
		&i.WillRenew,
		&i.ExpiresAt,
		&i.RcAppUserID,
		&i.UpdatedAt,
	)
	return i, err
}
