// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const anonymizeUserEvents = `-- name: AnonymizeUserEvents :exec
UPDATE referral_code_bonus.code_events
SET user_id = NULL
WHERE user_id = $1
`

// 刪除帳號。code_events 沒有外鍵（分區表），所以要自己把 user_id 抹掉；
// 抹掉而不是刪除，是因為那些曝光/點擊已經計入推薦碼的排序與品質分數，
// 整批刪掉會讓別人的碼排序莫名跳動。抹完就跟這個人無關了。
func (q *Queries) AnonymizeUserEvents(ctx context.Context, userID *uuid.UUID) error {
	_, err := q.db.Exec(ctx, anonymizeUserEvents, userID)
	return err
}

const countUsersAdmin = `-- name: CountUsersAdmin :one
SELECT count(*) FROM referral_code_bonus.users u
WHERE u.status <> 'deleted'
  AND ($1::text = '' OR u.email ILIKE '%' || $1::text || '%')
`

func (q *Queries) CountUsersAdmin(ctx context.Context, q_ string) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersAdmin, q_)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO referral_code_bonus.admins (email, password_hash, display_name, role)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, display_name, role, is_active, created_at
`

type CreateAdminParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	DisplayName  string `json:"display_name"`
	Role         string `json:"role"`
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (Admin, error) {
	row := q.db.QueryRow(ctx, createAdmin,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
		arg.Role,
	)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const createOAuthIdentity = `-- name: CreateOAuthIdentity :one
INSERT INTO referral_code_bonus.oauth_identities (user_id, provider, provider_user_id)
VALUES ($1, $2, $3)
RETURNING id, user_id, provider, provider_user_id, created_at
`

type CreateOAuthIdentityParams struct {
	UserID         uuid.UUID `json:"user_id"`
	Provider       string    `json:"provider"`
	ProviderUserID string    `json:"provider_user_id"`
}

func (q *Queries) CreateOAuthIdentity(ctx context.Context, arg CreateOAuthIdentityParams) (OAuthIdentity, error) {
	row := q.db.QueryRow(ctx, createOAuthIdentity, arg.UserID, arg.Provider, arg.ProviderUserID)
	var i OAuthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO referral_code_bonus.refresh_tokens (user_id, token_hash, family_id, expires_at, user_agent)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, token_hash, family_id, expires_at, rotated_at, revoked_at, user_agent, created_at
`

type CreateRefreshTokenParams struct {
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	FamilyID  uuid.UUID `json:"family_id"`
	ExpiresAt time.Time `json:"expires_at"`
	UserAgent string    `json:"user_agent"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.UserID,
		arg.TokenHash,
		arg.FamilyID,
		arg.ExpiresAt,
		arg.UserAgent,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.FamilyID,
		&i.ExpiresAt,
		&i.RotatedAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO referral_code_bonus.users (email, display_name, avatar_url, password_hash, email_verified_at, country)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, email, email_verified_at, display_name, avatar_url, password_hash, status, created_at, updated_at, country, avatar_public_id
`

type CreateUserParams struct {
	Email           string     `json:"email"`
	DisplayName     string     `json:"display_name"`
	AvatarUrl       *string    `json:"avatar_url"`
	PasswordHash    *string    `json:"password_hash"`
	EmailVerifiedAt *time.Time `json:"email_verified_at"`
	Country         *string    `json:"country"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.PasswordHash,
		arg.EmailVerifiedAt,
		arg.Country,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Country,
		&i.AvatarPublicID,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM referral_code_bonus.users WHERE id = $1
`

// 其餘子表靠外鍵處理：oauth_identities / refresh_tokens / referral_codes /
// subscriptions 是 ON DELETE CASCADE，code_reports.reporter_id 與
// subscription_events.user_id 是 ON DELETE SET NULL（回報內容留著但匿名）。
func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getAdminByEmail = `-- name: GetAdminByEmail :one
SELECT id, email, password_hash, display_name, role, is_active, created_at FROM referral_code_bonus.admins
WHERE lower(email) = lower($1::text) AND is_active
`

func (q *Queries) GetAdminByEmail(ctx context.Context, email string) (Admin, error) {
	row := q.db.QueryRow(ctx, getAdminByEmail, email)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getAdminByID = `-- name: GetAdminByID :one
SELECT id, email, password_hash, display_name, role, is_active, created_at FROM referral_code_bonus.admins WHERE id = $1 AND is_active
`

func (q *Queries) GetAdminByID(ctx context.Context, id uuid.UUID) (Admin, error) {
	row := q.db.QueryRow(ctx, getAdminByID, id)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getOAuthIdentity = `-- name: GetOAuthIdentity :one
SELECT id, user_id, provider, provider_user_id, created_at FROM referral_code_bonus.oauth_identities
WHERE provider = $1 AND provider_user_id = $2
`

type GetOAuthIdentityParams struct {
	Provider       string `json:"provider"`
	ProviderUserID string `json:"provider_user_id"`
}

func (q *Queries) GetOAuthIdentity(ctx context.Context, arg GetOAuthIdentityParams) (OAuthIdentity, error) {
	row := q.db.QueryRow(ctx, getOAuthIdentity, arg.Provider, arg.ProviderUserID)
	var i OAuthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, token_hash, family_id, expires_at, rotated_at, revoked_at, user_agent, created_at FROM referral_code_bonus.refresh_tokens WHERE token_hash = $1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.FamilyID,
		&i.ExpiresAt,
		&i.RotatedAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, email_verified_at, display_name, avatar_url, password_hash, status, created_at, updated_at, country, avatar_public_id FROM referral_code_bonus.users
WHERE lower(email) = lower($1::text) AND status <> 'deleted'
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Country,
		&i.AvatarPublicID,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, email_verified_at, display_name, avatar_url, password_hash, status, created_at, updated_at, country, avatar_public_id FROM referral_code_bonus.users
WHERE id = $1 AND status <> 'deleted'
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Country,
		&i.AvatarPublicID,
	)
	return i, err
}

const listUsersAdmin = `-- name: ListUsersAdmin :many
SELECT
    u.id, u.email, u.display_name, u.status, u.created_at,
    COALESCE(s.is_active, false) AND (s.expires_at IS NULL OR s.expires_at > now()) AS is_pro,
    s.expires_at  AS pro_expires_at,
    s.store       AS pro_store,
    s.product_id  AS pro_product_id
FROM referral_code_bonus.users u
LEFT JOIN referral_code_bonus.subscriptions s ON s.user_id = u.id
WHERE u.status <> 'deleted'
  AND ($3::text = '' OR u.email ILIKE '%' || $3::text || '%')
ORDER BY u.created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersAdminParams struct {
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
	Q      string `json:"q"`
}

type ListUsersAdminRow struct {
	ID           uuid.UUID  `json:"id"`
	Email        string     `json:"email"`
	DisplayName  string     `json:"display_name"`
	Status       string     `json:"status"`
	CreatedAt    time.Time  `json:"created_at"`
	IsPro        *bool      `json:"is_pro"`
	ProExpiresAt *time.Time `json:"pro_expires_at"`
	ProStore     *string    `json:"pro_store"`
	ProProductID *string    `json:"pro_product_id"`
}

// 後台的使用者查詢，客服/退款爭議時用來看誰是 Pro、手動補發或撤銷。
// is_pro 的判斷跟 s.isPro() 同一套邏輯（is_active 且未過期），這裡用 SQL 重算一次
// 是因為要一次列一頁，不能逐筆呼叫 Go 那個函式。
func (q *Queries) ListUsersAdmin(ctx context.Context, arg ListUsersAdminParams) ([]ListUsersAdminRow, error) {
	rows, err := q.db.Query(ctx, listUsersAdmin, arg.Limit, arg.Offset, arg.Q)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersAdminRow{}
	for rows.Next() {
		var i ListUsersAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.Status,
			&i.CreatedAt,
			&i.IsPro,
			&i.ProExpiresAt,
			&i.ProStore,
			&i.ProProductID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEmailVerified = `-- name: MarkEmailVerified :exec
UPDATE referral_code_bonus.users
SET email_verified_at = now(), updated_at = now()
WHERE id = $1 AND email_verified_at IS NULL
`

func (q *Queries) MarkEmailVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markEmailVerified, id)
	return err
}

const markRefreshTokenRotated = `-- name: MarkRefreshTokenRotated :exec
UPDATE referral_code_bonus.refresh_tokens SET rotated_at = now() WHERE id = $1
`

func (q *Queries) MarkRefreshTokenRotated(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markRefreshTokenRotated, id)
	return err
}

const revokeAllUserTokens = `-- name: RevokeAllUserTokens :exec
UPDATE referral_code_bonus.refresh_tokens
SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

// 重設密碼後把這個人的所有 session 作廢。會忘記密碼常常是因為帳號被別人拿走了，
// 只換密碼而留著既有的 refresh token 等於沒把對方踢出去。
func (q *Queries) RevokeAllUserTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserTokens, userID)
	return err
}

const revokeSubscription = `-- name: RevokeSubscription :execrows
UPDATE referral_code_bonus.subscriptions
SET is_active = false, will_renew = false, updated_at = now()
WHERE user_id = $1 AND is_active
`

// 客服手動撤銷 Pro（退款爭議、誤發）。只關掉 is_active，事件紀錄不動——
// 跟 RevenueCat webhook 進來的撤銷用同一份狀態，之後真的 webhook 送到時會再 upsert 一次。
func (q *Queries) RevokeSubscription(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSubscription, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeTokenFamily = `-- name: RevokeTokenFamily :exec
UPDATE referral_code_bonus.refresh_tokens
SET revoked_at = now()
WHERE family_id = $1 AND revoked_at IS NULL
`

// 偵測到舊 token 被重用時整族撤銷：那代表 token 外洩，該裝置全部作廢。
func (q *Queries) RevokeTokenFamily(ctx context.Context, familyID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeTokenFamily, familyID)
	return err
}

const updateUserAvatar = `-- name: UpdateUserAvatar :one
UPDATE referral_code_bonus.users
SET avatar_url = $2, avatar_public_id = $3, updated_at = now()
WHERE id = $1
RETURNING id, email, email_verified_at, display_name, avatar_url, password_hash, status, created_at, updated_at, country, avatar_public_id
`

type UpdateUserAvatarParams struct {
	ID             uuid.UUID `json:"id"`
	AvatarUrl      *string   `json:"avatar_url"`
	AvatarPublicID *string   `json:"avatar_public_id"`
}

// 只動大頭照。走 UpdateUserProfile 的話得把顯示名稱與所在地一起送，
// 上傳圖片的當下前端手上那份可能已經是舊的。
func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserAvatar, arg.ID, arg.AvatarUrl, arg.AvatarPublicID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Country,
		&i.AvatarPublicID,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE referral_code_bonus.users
SET password_hash = $2, updated_at = now()
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash *string   `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE referral_code_bonus.users
SET display_name = $2, avatar_url = $3, country = $4, updated_at = now()
WHERE id = $1
RETURNING id, email, email_verified_at, display_name, avatar_url, password_hash, status, created_at, updated_at, country, avatar_public_id
`

type UpdateUserProfileParams struct {
	ID          uuid.UUID `json:"id"`
	DisplayName string    `json:"display_name"`
	AvatarUrl   *string   `json:"avatar_url"`
	Country     *string   `json:"country"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Country,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Country,
		&i.AvatarPublicID,
	)
	return i, err
}
